### ISSUE TITLE
Suggestions for removing completed jobs

### ISSUE THREAD

**Issue by chafey** [vsivsi/meteor-job-collection#101]
Any suggestions on how best to remove completed jobs?  I could use a cron type package to periodically query for completed jobs and remove them, but wanted to check and see if there was a better way.  It would sure be nice if the package handled this for you - perhaps a "removeAfter" which would remove a completed job after it has been completed for the specified time (e.g. 4 hours)

**Comment by vsivsi** [comment]
Hi, there's no reason to use *another* cron package to do periodic cleanup of old jobs, job-collection itself can create jobs that run periodically and perform housekeeping functions! It's the main reason why I haven't added a `removeAfter` as you (and others) have suggested, because it's so easy to do yourself, and then you can customize the logic to your heart's content.

The "playground" sample app shows one way to do it here: 
https://github.com/vsivsi/meteor-job-collection-playground/blob/master/play.coffee#L443-L464

I almost added such a feature from the very beginning, but I just couldn't convince myself that there was a simple feature that would cover 80%+ of cases. In my own app code, I kept running into special cases where I didn't want the default "remove" behavior, and so it because simpler to just write a simple cleanup job that meets the needs of each app. Anything job-collection did internally would be essentially the same code as I link to above, but then you wouldn't be able to easily customize it...

**Comment by chafey** [comment]
OK this makes sense, closing this issue
