### ISSUE TITLE
Low-Frequency jobs (long gap between runs)

### ISSUE THREAD

**Issue by KrishnaPG** [vsivsi/meteor-job-collection#102]
The wait times and other time-related parameters in this package are mostly specified in the usual micro-second resolution, which is fine for many applications.

We have many jobs, but all their repeat period is once-per-day (and some once-per weak etc).

Trying to understand, what is the implication of this on the host resource utilization. What parameters can be adjusted so that we get optimal performance for such long delayed, low-frequency jobs. For example, inside the package if there is some poller trying to poll for new 'ready jobs' at sub-second frequencies, then making it poll for every couple of hours could be a good options for our scenarios. 

Ofcourse, this all is assuming that the package is using some kind of poll. If it is not, then I think this becomes irrelevant. In such cases, what others pointers we should keep in mind (to configure) so that we do not make the internal package engines do unnecessary work?

The piont I am trying to understand is: given our knowledge that our jobs have long-delays between runs, how best to convey this knowledge to the package so that it can keep the resource utilization (if any) to be low.

**Comment by vsivsi** [comment]
The server side of a job-collection only polls to determine when there are waiting jobs that are now ready to run (their wait time is over). This is "promotion" poll is necessary because there is no way to write an observable query to trigger this: time is changing, not the database. 

The server call `jc.promote([milliseconds])` controls how often the promotion query runs. By default it runs every 15 seconds, but that can be set to whatever value your app requires. 

The other place where polling can occur is with workers repeatedly requesting work when none is available. If you use `jc.processJobs()` to create workers, you can set their polling interval using the `pollInterval` option to that call (default is 5 seconds).  Even better, you can setup an observe query on the JobCollection, set `pollInterval` to false, and then use `q.trigger()` to trigger a job request work when it becomes available, eliminating all worker polling. See the sample apps for examples of this.

**Comment by KrishnaPG** [comment]
Thanks much. That information is helpful.
