### ISSUE TITLE
Recommended way to update/overwrite existing job options?

### ISSUE THREAD

**Issue by voidale** [vsivsi/meteor-job-collection#109]
Hello Vaughn! 

Is it possible to overwrite Job.repeat or update for existing job in the collection? 

I'm trying to update the later js schedule but looking at the docs or trying to fetch the job using `j = new Job(jc, jobDoc)` and doing .save() has no effect and no new job either.

My use case is like this:
1. user picks on client side a later js schedule (just one needs to be unique) something like: 
`later.parse.recur().on('12:15', '16:25').time().onWeekday()` 
2. we create a job for this schedule.
3. user changed his schedule how we update job? 

Thanks you for taking the time answering all my random questions

**Comment by vsivsi** [comment]
Yes, of course.  You just need get a valid Job object for the job, pause it, make the changes you want, and then save the changes (it should automatically resume on save).

```js
// Code below assumes server/fibers, works with callbacks as well.

var job = jc.getJob(_id);
// Or, equivalently...
// var job = new Job (jc, jc.findOne(_id));
job.pause();
job.repeat(...);
job.save();
```

See this state diagram for a visual explanation: https://github.com/vsivsi/meteor-job-collection#jcjobstatuspausable---anywhere

**Comment by voidale** [comment]
@vsivsi Aha! The secret was to pause it :) thank you really appreciate your help.

**Comment by voidale** [comment]
@vsivsi Hi Vaughn again, I'm trying to replace later object with my own later object (where I have timezone support) can you recommend me the best way of doing that? I thought about creating a copy of the package and add my later js package as a dependency but It will be harder to maintain any updates

**Comment by vsivsi** [comment]
Hi, forking the project does seem the most straightforward, but has the issue of merging upstream changes back into you fork as you mention. 

Unfortunately when I added the later.js support, I didn't anticipate this case and make it more pluggable.  

Is your timezome enhanced later.js otherwise compatible with vanilla later.js?  Specifically, do the schedule objects serialize to essentially the same schema?  Job collection isn't very thorough in validating these objects, so there may be enough wiggle room if you haven't made radical changes. 
See the validation rule here: https://github.com/vsivsi/meteor-job-collection/blob/master/src/shared.coffee#L48

Also, is your timezome enhanced version backward compatible with schedules crated by the vanilla version?  If so, I would consider a PR using your new version instead of mrt:later. You are not the first nor the last to want TZ support in JC+later, so that would be a nice addition, but it would need to backwards compatible.

**Comment by voidale** [comment]
Hey,

Adding the later JS to support time zone actually is straightforward no
hacks UTC/local time still work the same just new option to pick time zone.
If merging is an option that's great I will take a look tomorrow, I might
also improve the later JS time zone to work with moment JS timezone before
so it will be nice and good for everyone. Thanks.

**Comment by voidale** [comment]
@vsivsi sorry being late but here is the package for later js with time zone support: https://atmospherejs.com/voidale/later-js-tz I tried adding momentjs but it gets complicated so I just decided to keep it with https://github.com/bigeasy/timezone it works great. You can see the changes are really small if it's possible to add optional later js support and then it will be possible to use which ever package the people choose. I also updated later.js and not sure if it's uptodate with mrt:later

**Comment by vsivsi** [comment]
@voidale  Wow, this looks great. Nice job! Also, I didn't know about `bigeasy/timezone`, that's a nice find, I wish I had had it for a couple of projects I worked on last year!  

I'll try this out tonight. Is there any chance you can add some simple unit tests to `voidale/later-js-tz` that run with `meteor test-packages`?  Doesn't need to be exhaustive, but some basic stuff that shows it's working, similar to your example code and output.

Thanks!

**Comment by voidale** [comment]
@vsivsi yes of course I will add those tests and improve it further, I will need updated IANA time zone database. So I will probably create a meteor package for `bigeasy/timezone` to update IANA database manually because it's important to be uptodate in my application with latest timezone changes. Had a chance to review? Can we easily adapt this to job-collection? :) Thanks!

**Comment by vsivsi** [comment]
Hi @voidale , sorry, I lost track of this discussion because it's sitting at the bottom of a closed issue...

How is this going?  Probably the easiest way to proceed when you are ready is for you to put together a PR for job-collection that uses your new `later-js-tz` package instead of `mrt:later`.  And then make sure that there are adequate integration tests added to job-collection.

I'm currently be very conservative about changes to job-collection because many people are using it in production and I have limited time to spend on this through the end of the year...  So the more you can pitch-in and make my job easy, the sooner we can get this cool new feature into the package!  :smile:
