### ISSUE TITLE
"Error: Match error: Failed Match.Where validation in field retries" on job creation...

### ISSUE THREAD

**Issue by harmon25** [vsivsi/meteor-job-collection#117]
This package was working great for me...
But have started getting this error when trying to start a job
Stubbed out my entire jobs, that were running fine before to test, still getting the error.
Seems to be a problem inserting the job into mongo?
Related to the retries field on the job which i am not attempting to set?

## queue
```javascript
var queue = jc.processJobs(
// Type of job to request
// Can also be an array of job types
'addModules', {
    concurrency: 3,
    payload: 1,
    //do not poll, run job with queue.trigger();
    pollInterval: 1000000000,
    prefetch: 1
},
// job function - the actual worker
function(job, callback) {
    if (job.type === 'addModules') {
    console.log(job.type)
    // retreive module array
    var mods = msfAPICmd(job.data.cmd);
    // pass array for processing..sync..
    insertModules(mods, job.data.cat, job);
    // when the above is complete...
    job.log("Inserted " + apiCmd.cat);

    // Only called when there is a valid job
    job.done('done');
    callback();
};
});
```
## creating job
```javascript
var aJob = new Job(jc, 'addModules',
 {cmd:'api.cmd', cat:'category'})
.priority("normal")
.save();

queue.trigger();
```
### Here is the error message am getting on the server console:
```
JobQueue: Received error from getWork():  { [Error: Match error: Failed Match.OneOf or Match.Optional validation]
 message: 'Match error: Failed Match.OneOf or Match.Optional validation',
 path: '',
 sanitizedError: 
 { [Error: Match failed [400]]
    error: 400,
    reason: 'Match failed',
    details: undefined,
    message: 'Match failed [400]',
   errorType: 'Meteor.Error' },
errorType: 'Match.Error' }

/home/harmon/.meteor/packages/meteor-tool/.1.1.9.1pep24e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
         throw(ex);
               ^
Error: Match error: Failed Match.Where validation in field retries
  at checkSubtree (packages/check/packages/check.js:231:1)
  at packages/check/packages/check.js:301:1
  at Function._.each._.forEach (packages/underscore/packages/underscore.js:142:1)
  at checkSubtree (packages/check/packages/check.js:298:1)
  at check (packages/check/packages/check.js:40:1)
  at JobCollectionBase._DDPMethod_jobSave (packages/vsivsi_job-collection/packages/vsivsi_job-collection.js:2515:1)
  at JobCollection.<anonymous> (packages/vsivsi_job-collection/packages/vsivsi_job-collection.js:3220:1)
  at packages/vsivsi_job-collection/packages/vsivsi_job-collection.js:3128:1
  at methodCall (packages/vsivsi_job-collection/packages/vsivsi_job-collection.js:36:1)
  at Job.save (packages/vsivsi_job-collection/packages/vsivsi_job-collection.js:1135:1)
```
## Help is much appreciated, thanks!

**Comment by vsivsi** [comment]
Hi, I'm a little confused.  The title of this issue says you are getting an error on `job.save()` but the issue body itself doesn't provide any information on that...  It shows an error from `getWork()` instead,

I guess my first question is, what else changed between when everything was working fine and when you started getting these match errors?  Also, tell me a bit more about your seltup:  What platform, what version of job-collection, and if you are using node.js workers, what version of the meteor-job npm package?

Have you tried running `meteor reset` in your project directory to clear out the MongoDB state? Does that make a difference?

So, the match error in the issue title would indicate that when you are trying to save the job, the `retries` field is invalid. That check is here: https://github.com/vsivsi/meteor-job-collection/blob/master/src/shared.coffee#L69  

Basically it needs to be an integer >= 0. It is set to 0 by default when the job object is created, so if you are getting this error, either something is going very wrong with job creation, or somehow the object is being directly modified before you save it. What value do you see if you do:

```js
var aJob = new Job(jc, 'addModules',
    {cmd:'api.cmd', cat:'category'})
 .priority("normal");
console.log("Value of retries: ", aJob.doc.retries);  // Should be 0 !!
aJob.save();
``` 
The other Match error you are getting on `getWork()` indicates that it is being called with invalid parameters or options.  It has pretty basic requirements:  https://github.com/vsivsi/meteor-job-collection/blob/master/src/shared.coffee#L392-L395

But again, since you are calling this via `processJobs()`, that should all be handled for you. I don't see anything obviously wrong with the code you've included, but the only way I can try to reproduce this and help you further is if you create a minimal repro project as a full Meteor app and commit it as a project here on github. That way I can run exactly the same code as you are. Trying to debug your program remotely via messages like this will be a waste of both of our time.

**Comment by harmon25** [comment]
I rewrote a node module for accessing an API.

**Comment by harmon25** [comment]
I am using a node module I wrote to access an API: https://github.com/harmon25/msfrpc-client.
It was working fine with bluebird promises..but written in es6 and compiled with babel seems to cause some odd issues.

Simply including the module with meteorhacks:npm:  ``` var msfClient = Meteor.npmRequire('msfrpc-client-node');``` causes the ```Error: Match error: Failed Match.Where validation in field retries```

I am probably going to have to revert the node module back to bluebird promises, I do not understand how that could interfere with job collection so badly, as it seems to work OK when I do not create a JobCollection, queue and job...

**Comment by vsivsi** [comment]
That's indeed very strange. I'll try out he code above and see what I can reproduce.

**Comment by vsivsi** [comment]
Hi, yes I can repro this with your code above. There's something incompatible about these two packages... I'm looking into it now.

**Comment by vsivsi** [comment]
Okay, I got to the bottom of it.  The problem is definitely in your npm package code someplace.

This has nothing to do with job-collection.  The issue is that somewhere, somehow in your npm package, 
the javascript global `Number` is changing.

So you can strip out all of the job-collection code and replace it with a simple test:

```js
if (Meteor.isServer) {
   Meteor.startup(function() {
      // this seems to cause the error, even if it is not being utilized at all...
      var msfClient = Meteor.npmRequire('msfrpc-client-node');
      check(1, Number);  // Throws when above line isn't commented out...
 });
}

```

I have no idea what is happening to cause this, but it's BAD!

**Comment by vsivsi** [comment]
Also note: This is somehow specific to `Number`.  If use use `check("1", String);` instead, everything works fine.

**Comment by harmon25** [comment]
Thank you so much for helping me get to the bottom of this.
Guess i am going back to bluebird + es5...

**Comment by vsivsi** [comment]
Good luck!
