### ISSUE TITLE
How to run jobs parallel / spin up worker servers?

### ISSUE THREAD

**Issue by satyavh** [vsivsi/meteor-job-collection#132]
Question, I understand workers can run anywhere. My workers need a long time to process a job, so I want to run them in parallel on different worker servers.

So what if I setup 5 servers, I create 10 jobs.  How do I 'load balance' the jobs over the servers/workers? How to make sure that not all 5 servers pick up the same job?

Is that possible?

Even better, would it be possible to spin up a worker server - perhaps even a docker container - to process the job?

**Comment by vsivsi** [comment]
Hi, the same job will never be issued to more than one worker.  If you use `processJobs()` to schedule your workers on each machine, then you can control the level of parallelism (number of simultaneous jobs) that will run on each machine. The worker machine's should stochastically load-balance pretty well by using either polling (the default) or the observe-based mechanism using the `q.trigger()` call. https://github.com/vsivsi/meteor-job-collection#qtrigger---anywhere

Worker queues setup using process jobs can be monitored for utilization and can be cleanly shutdown using the included calls.  However, job-collection is not a cluster/cloud manager, in that it knows nothing about how to spin-up or shutdown workers based on workload. There are other packages that do that kind of thing that could probably be integrated with jobCollection.

The job collection playground sample app shows a very rudimentary mechanism for determining the number of workers currently connected, and it is possible to create a job that shuts down the worker it is assigned to. The system is very flexible, but there are so many cloud/cluster deployment possibilities and possible policies that I have made no attempt to implement any of this for jobCollection because there is no "80% solution" that will cover most project needs.

**Comment by satyavh** [comment]
Thanks for your fast reply. That's really awesome, I'm going to try that out. 

"There are other packages that do that kind of thing that could probably be integrated with job-collection."
Could you give me a hint which packages you're referring to? Thanks

**Comment by vsivsi** [comment]
You should google "horizonal scaling with node.js" or similar and the results should get you started,

**Comment by satyavh** [comment]
Ok thanks a lot.
