### ISSUE TITLE
Schedule not working as expected

### ISSUE THREAD

**Issue by luixal** [vsivsi/meteor-job-collection#148]
Hi,

I'm having some trouble trying to schedule jobs. It works, but doesn't take timing really serious :P

Here's my init and processJobs code (don't worry about security, it's just for make the example sorter):

```javascript
jobs = JobCollection('jobs');
jobs.allow({
  // Grant full permission to any authenticated user
  admin: function (userId, method, params) {
    return true;
  }
});


jobs.processJobs(
  'log2console',
  {},
  function(job, callback) {
    // processing job..
    console.log('>> ' + job.data.message + ' (' + moment().format('HH:mm:ss') + ')');
    job.done();
    callback();
  }
);
```
this is the code I'm using for scheduling jobs:

```javascript
var job = new Job(jobs, 'log2console', {message: 'hi world!');
job.repeat({schedule: jobs.later.parse.text('every 1 sec')});
job.save();
```

aaand... it doesn't appear to run every second. This is the output I get in server's console:

```
I20160120-18:25:47.378(1)? >> hi world! (18:25:47)
I20160120-18:25:57.388(1)? >> hi world! (18:25:57)
I20160120-18:25:57.482(1)? >> hi world! (18:25:57)
I20160120-18:25:57.560(1)? >> hi world! (18:25:57)
I20160120-18:25:57.609(1)? >> hi world! (18:25:57)
I20160120-18:25:57.686(1)? >> hi world! (18:25:57)
I20160120-18:25:57.731(1)? >> hi world! (18:25:57)
I20160120-18:25:57.810(1)? >> hi world! (18:25:57)
I20160120-18:26:12.412(1)? >> hi world! (18:26:12)
I20160120-18:26:12.505(1)? >> hi world! (18:26:12)
I20160120-18:26:12.552(1)? >> hi world! (18:26:12)
I20160120-18:26:12.630(1)? >> hi world! (18:26:12)
I20160120-18:26:12.709(1)? >> hi world! (18:26:12)
I20160120-18:26:12.790(1)? >> hi world! (18:26:12)
I20160120-18:26:12.865(1)? >> hi world! (18:26:12)
I20160120-18:26:27.483(1)? >> hi world! (18:26:27)
I20160120-18:26:27.528(1)? >> hi world! (18:26:27)
I20160120-18:26:27.590(1)? >> hi world! (18:26:27)
I20160120-18:26:27.637(1)? >> hi world! (18:26:27)
I20160120-18:26:27.699(1)? >> hi world! (18:26:27)
```

Same happends if I set it to 5 secs, 1 min, 5mins... there's always a discrepancy in time past from last execution.

Any ideas what am I doing wrong?

Thanks!

**Comment by vsivsi** [comment]
Hi, you should see the documentation for `jc.promote()`.  In a nutshell: The job-collection server has to poll for jobs that were previously `waiting` but can now be changed to `ready`. (You can't reactively `observe` this because the database isn't changing, time is...)

`jc.promote()` sets this polling interval, with a default of 15s. If you care about sub 1s timing of jobs, then you should set the promote interval to less than 500ms.

Another source of delay is in how your worker(s) are configured to ask for new work when idle. When using `jc.processJobs()`, the default is that workers will poll the server asking for available work every 5s. You can set this to a lower value using the `pollInterval` option. Or, even better, you can disable worker polling (`pollInterval: false`) and instead use a `observe` based mechanism to [trigger requests for new work as it becomes available](https://github.com/vsivsi/meteor-job-collection#qtrigger---anywhere).

**Comment by vsivsi** [comment]
One other point is that the delay in repeating jobs is from the completion of the previous job, not from when it is scheduled...  So if you schedule a repeating job to run every 5 seconds, but each run of the job takes 15 seconds to run, then at most it will only run 3 times per minute.

Put another way, there will never be more than one running instance of a repeating job, scheduling of the next instance always waits until the current one is finished.

If you need a job to run once per minute no matter how long previous instances of the job take to complete, then you will need to schedule those jobs individually. 

A final note is that job-collection (like Meteor.js/node.js) is a "best effort" system. There are any number of reasons why jobs might not run exactly when you request them to (polling delays, server down, workers all busy....)

**Comment by luixal** [comment]
Hi,

Sorry for the delay, had read this on it day, but just had to jump to some critical issues at work :(

Thanks for all the info, I guessed it was something like this, but didn't know for sure. Thing is I don't need a job to be run at an specific time (just wasn't sure I was doing things right) so it fits perfectly for my system.

Thanks!
