### ISSUE TITLE
update meteor docs

### ISSUE THREAD

**Issue by JulianKingman** [vsivsi/meteor-job-collection#150]
In the example in the quick start documentation it has the following:
````javascript
var workers = Job.processJobs('myJobQueue', 'sendEmail',
      function (job, cb) {
````
This had me scratching my head as I got ````Error: in optionsHelp options not an object or bad callback```` errors, until I saw in other examples that in Meteor "Job" is replaced by the name given to the JobCollection, and "myJobQueue" is omitted as a parameter altogether. A note about that would be super helpful, as the comments say that can be dropped into meteor pretty much as is.

Thanks!

**Comment by vsivsi** [comment]
Hi, the example code you are referencing is plain (non-Meteor) node.js code using the [meteor-job npm package](https://www.npmjs.com/package/meteor-job).  That package has a slightly different API, because only the `Job` object can exists outside of the Meteor environment.

Directly above that code block it says:

> Below is a pure node.js program that can obtain jobs from the server above and "get 'em done". Powerfully, this can be run anywhere that has node.js and can connect to the server. The secret sauce here is the meteor-job npm package, which is fully interoperable with job-collection.
> 
> NOTE! Worker code very similar to what is shown below (without all of the DDP setup) can also run on the Meteor server or even in a Meteor client. Everything before the call to Job.processJobs() is just code to connect and authenticate a pure node.js script with a Meteor server.

I will add a comment in the sample code pointing out that `processJobs` is a method of `jC` in the Meteor environment.

Thanks

**Comment by JulianKingman** [comment]
Great, thank you!
