### ISSUE TITLE
Stuck queue

### ISSUE THREAD

**Issue by wallslide** [vsivsi/meteor-job-collection#158]
I'm having trouble with work just piling up in the queue. The jobs get promoted to the ready state, but no work gets processed. In order to fix this, I have to restart my servers (3 containers running on galaxy). It seems like to get all of the jobs processed, I have to restart all of my servers... like some of them have an indefinite 'hold' on ready jobs in the queue. For each server that I kill and then gets restarted, a certain portion of the stuck work in the queue gets processed. Eventually when I kill all of the servers, all of the work gets processed.  This problem is very intermittent however... happening perhaps 2 or 3 times a week.

Any ideas would be appreciated. Love the package, using it more and more.

I have a JobQueue that looks like this:

```javascript
ShopifyJobsQueue = JobCollection('shopifyJobsQueue');
ShopifyJobsQueue.allow({
  // Grant full permission to any authenticated user
  admin: function(userId, method, params) {
    return (Users.isStaff(userId) || Users.isAdmin(userId));
  },
});
```

and several workers that look like this:

```javascript
let loadRiskQ = ShopifyJobsQueue.processJobs('loadRisk', {
  pollInterval: 5000,
  workTimeout: 15000,
}, (job, callback)=> {
  let {shopifyOrderId} = job.data;
  try {
    ShopifyFulfillmentService.loadRisks({shopifyOrderId});
    job.done();
  } catch (err) {
    console.log('loadRisk fail');
    console.error(err.stack);
    job.fail(err.toString());
  }
  callback();
});

ShopifyJobsQueue.find({type: 'loadRisk', status: 'ready'})
  .observe({
    added: function() {
      loadRiskQ.trigger();
    }
  });
```

and then later of course this:
```javascript
ShopifyJobsQueue.startJobServer();
```

Each worker has a workTimeout set.
It seems like even if I failed to call `job.done()` or `callback()` somewhere that the workTimeout setting should still allow the processing of jobs to continue.

I tried to implement a way to restart the queue so that at least the other staff here can get things rolling without needing me to restart the servers. Unfortunately without being able to reproduce the problem in a dev environment means I am kind of taking stabs in the dark trying to figure out implement even a stopgap solution. The following did not work for me:

```javascript
ShopifyJobsQueue.shutdownJobServer({
      timeout: 10000,
    });
ShopifyJobsQueue.startJobServer();
```

**Comment by vsivsi** [comment]
Hmmm.  This is the first I've heard of something like this.  When you say "no work gets processed", what is actually happening in the queue?  Are all of the jobs `'ready`' or are some `'running'` and just never completing successfully?  From your description, this sounds more like something going wrong with your workers (connectivity), than with the servers.  Example: you have N workers, and randomly they are losing connectivity/authentication with the servers, but restarting the servers somehow resets the connections (or are you restarting the workers at the same time?) 

Here are some potential types of issues to ponder...

What are your workers? Are they plain node.js scripts using the DDP npm package to connect? Are you handling all of the connection events? Do you reauthenticate in the event the connection drops and is reconnected (`wasReconnect` parameter in the `DDP.connnect()` callback)? How long is an authentication token valid on your servers? Have you tried [turning on logging](https://github.com/vsivsi/meteor-job-collection#logging) to see all of the server activity when it gets "stuck"? 

Another thing to try is writing a test worker script that just tries to do a [`jc.getWork()`](https://github.com/vsivsi/meteor-job-collection#jcgetworktype-options-callback---anywhere) and run that against a "stuck" server to see (in conjunction with logging) what might be happening. 

There's really very little on the server side to get "stuck", it's just a bunch of Meteor.methods under the hood, like everything else in Meteor. If the server is alive at all, then it should be responding to method calls, if it's doing that, then workers should be able to get and complete work. I'm inferring that you can continue to *add* jobs to a "stuck" queue, which means that everything on the server side is still capable of accessing the underlying collection, which is what leads me to wonder about worker connection/authentication handling.  Meteor/DDP is really not designed for "forever" connections, and so long lived workers will need to handle these types of issues to stay online.

I'm basically just brainstorming here, as debugging intermittent deployment problems via github issue is pretty much impossible. I'm happy to bounce ideas back and forth, but without access to your code and systems, that's about the best I can do.

**Comment by vsivsi** [comment]
Another thing to try to tease this apart.

If you create a type of "testJob" and create a "testJob" worker in your server code (on the same JobCollection) such that you eliminate the potential connection issues (all calls are local within a server instance), does that worker continue to process jobs, even when the server is "stuck" for "remote" workers?

**Comment by wallslide** [comment]
I'll try out the experiments that you propose. In the meantime:

1. The workers are all running on meteor servers. This means that restarting the servers also necessarily means restarting the workers.
2. When I say that the jobs are stuck, I mean that they are in the `ready` state but not getting processed.
3. I'll verify if there are any jobs stuck in the `running` state, but I'm pretty sure I've checked that and the answer is no, there are none.
4. Yes, jobs can still be added to the queue, and are being promoted to the `ready` state.

Thanks for your help.

**Comment by vsivsi** [comment]
For reference, this seems like a similar issue...  https://github.com/vsivsi/meteor-job/issues/7

**Comment by wallslide** [comment]
Last night some jobs got stuck. I did a little digging and this is what I found:

1. There are no zombie 'running' jobs.
2. Only one type of job gets stuck. The rest continue processing just fine.

I was thinking maybe I was doing something stupid during the job creation, causing those jobs to be stuck? I've pasted two of the jobs which were stuck down below:

```
{ 
    "_id" : "3SrR5EubScz2vLaQP", 
    "runId" : null, 
    "type" : "receivedShopifyOrder", 
    "data" : {
        "shopifyOrderId" : 2.630557447E9
    }, 
    "status" : "ready", 
    "updated" : ISODate("2016-03-03T01:00:26.027+0000"), 
    "created" : ISODate("2016-03-03T00:45:05.243+0000"), 
    "priority" : NumberInt(0), 
    "retries" : NumberInt(4), 
    "retryWait" : NumberInt(60000), 
    "retried" : NumberInt(4), 
    "retryBackoff" : "exponential", 
    "retryUntil" : ISODate("275760-09-13T00:00:00.000+0000"), 
    "repeats" : NumberInt(0), 
    "repeatWait" : NumberInt(300000), 
    "repeated" : NumberInt(0), 
    "repeatUntil" : ISODate("275760-09-13T00:00:00.000+0000"), 
    "after" : ISODate("2016-03-03T01:00:20.272+0000"), 
    "progress" : {
        "completed" : NumberInt(0), 
        "total" : NumberInt(1), 
        "percent" : NumberInt(0)
    }, 
    "depends" : [

    ], 
    "resolved" : [

    ], 
    "log" : [
        {
            "time" : ISODate("2016-03-03T00:45:05.243+0000"), 
            "runId" : null, 
            "level" : "info", 
            "message" : "Constructed"
        }, 
        {
            "time" : ISODate("2016-03-03T00:45:05.243+0000"), 
            "runId" : null, 
            "message" : "Job Submitted", 
            "level" : "info"
        }, 
        {
            "time" : ISODate("2016-03-03T00:45:05.245+0000"), 
            "runId" : null, 
            "message" : "Promoted to ready", 
            "level" : "info"
        }, 
        {
            "time" : ISODate("2016-03-03T00:45:05.264+0000"), 
            "runId" : "q8seewJD7F6jir3Lm", 
            "message" : "Job Running", 
            "level" : "info"
        }, 
        {
            "time" : ISODate("2016-03-03T00:45:06.595+0000"), 
            "runId" : "q8seewJD7F6jir3Lm", 
            "message" : "Job Failed with Error: missing saasu invoice.", 
            "level" : "warning"
        }, 
        {
            "time" : ISODate("2016-03-03T00:46:10.982+0000"), 
            "runId" : null, 
            "message" : "Promoted to ready", 
            "level" : "info"
        }, 
        {
            "time" : ISODate("2016-03-03T00:46:11.013+0000"), 
            "runId" : "TSWZFpmEooXtChyfq", 
            "message" : "Job Running", 
            "level" : "info"
        }, 
        {
            "time" : ISODate("2016-03-03T00:46:12.343+0000"), 
            "runId" : "TSWZFpmEooXtChyfq", 
            "message" : "Job Failed with Error: missing saasu invoice.", 
            "level" : "warning"
        }, 
        {
            "time" : ISODate("2016-03-03T00:48:14.128+0000"), 
            "runId" : null, 
            "message" : "Promoted to ready", 
            "level" : "info"
        }, 
        {
            "time" : ISODate("2016-03-03T00:48:14.165+0000"), 
            "runId" : "LGYcbP5PQ2pRQ2hzT", 
            "message" : "Job Running", 
            "level" : "info"
        }, 
        {
            "time" : ISODate("2016-03-03T00:48:15.442+0000"), 
            "runId" : "LGYcbP5PQ2pRQ2hzT", 
            "message" : "Job Failed with Error: missing saasu invoice.", 
            "level" : "warning"
        }, 
        {
            "time" : ISODate("2016-03-03T00:52:19.039+0000"), 
            "runId" : null, 
            "message" : "Promoted to ready", 
            "level" : "info"
        }, 
        {
            "time" : ISODate("2016-03-03T00:52:19.078+0000"), 
            "runId" : "DRhuuhFFkDrxFzXAm", 
            "message" : "Job Running", 
            "level" : "info"
        }, 
        {
            "time" : ISODate("2016-03-03T00:52:20.274+0000"), 
            "runId" : "DRhuuhFFkDrxFzXAm", 
            "message" : "Job Failed with Error: missing saasu invoice.", 
            "level" : "warning"
        }, 
        {
            "time" : ISODate("2016-03-03T01:00:26.027+0000"), 
            "runId" : null, 
            "message" : "Promoted to ready", 
            "level" : "info"
        }
    ], 
    "workTimeout" : NumberInt(15000), 
    "expiresAfter" : ISODate("2016-03-03T00:52:34.077+0000"), 
    "failures" : [
        {
            "value" : "missing saasu invoice", 
            "runId" : "q8seewJD7F6jir3Lm"
        }, 
        {
            "value" : "missing saasu invoice", 
            "runId" : "TSWZFpmEooXtChyfq"
        }, 
        {
            "value" : "missing saasu invoice", 
            "runId" : "LGYcbP5PQ2pRQ2hzT"
        }, 
        {
            "value" : "missing saasu invoice", 
            "runId" : "DRhuuhFFkDrxFzXAm"
        }
    ]
}
```

and another

```
{ 
    "_id" : "HrJbeqqgqAEQTzAoz", 
    "runId" : null, 
    "type" : "receivedShopifyOrder", 
    "data" : {
        "shopifyOrderId" : 2.629806791E9
    }, 
    "status" : "ready", 
    "updated" : ISODate("2016-03-03T00:56:08.419+0000"), 
    "created" : ISODate("2016-03-03T00:56:08.416+0000"), 
    "priority" : NumberInt(0), 
    "retries" : NumberInt(1), 
    "retryWait" : NumberInt(0), 
    "retried" : NumberInt(0), 
    "retryBackoff" : "exponential", 
    "retryUntil" : ISODate("275760-09-13T00:00:00.000+0000"), 
    "repeats" : NumberInt(0), 
    "repeatWait" : NumberInt(300000), 
    "repeated" : NumberInt(0), 
    "repeatUntil" : ISODate("275760-09-13T00:00:00.000+0000"), 
    "after" : ISODate("2016-03-03T00:56:08.419+0000"), 
    "progress" : {
        "completed" : NumberInt(0), 
        "total" : NumberInt(1), 
        "percent" : NumberInt(0)
    }, 
    "depends" : [

    ], 
    "resolved" : [

    ], 
    "log" : [
        {
            "time" : ISODate("2016-03-03T00:56:08.416+0000"), 
            "runId" : null, 
            "level" : "info", 
            "message" : "Constructed"
        }, 
        {
            "time" : ISODate("2016-03-03T00:56:08.416+0000"), 
            "runId" : null, 
            "message" : "Job Submitted", 
            "level" : "info"
        }, 
        {
            "time" : ISODate("2016-03-03T00:56:08.419+0000"), 
            "runId" : null, 
            "message" : "Promoted to ready", 
            "level" : "info"
        }
    ]
}
```
also, the code that I use to create the jobs:
```javascript
receiveShopifyOrder: function({shopifyOrderId, retries, wait}) {
    var receivedShopifyOrderJob = new Job(ShopifyJobsQueue, 'receivedShopifyOrder', {
        shopifyOrderId,
      }
    )
      .retry({
        retries,
        wait,
        backoff: 'exponential',
      })
      .save();
  },
```
and the two ways that I call it:
```javascript
ShopifyFulfillmentService.receiveShopifyOrder({shopifyOrderId, retries: 0, wait: 0});
```
```javascript
ShopifyFulfillmentService.receiveShopifyOrder({shopifyOrderId, retries: 7, wait: 60000});
```

**Comment by vsivsi** [comment]
Hi, that's interesting, but what would be most useful would be to see the *worker* code (the function called by `jc.processJobs()`).  It's not the *jobs* that are stuck, it's the worker that should be working on them but apparently isn't.  My hypothesis is entirely consistent with your observation that only one type of job is stuck, while others continue to process.  My guess is that you have different workers for each job type (each with its own call to `jc.processJobs()`), and so the jobs above aren't processing because all of the workers for that job type are stuck.  And the mostly likely way that they are getting stuck is that your code is somehow returning (or throwing) out of the worker function without calling the callback function so that `jc.processJobs()` knows that invocation of the worker function is done (calling `job.done()` or `job.fail()` is not sufficient, you must call the callback!).

**Comment by Chugot** [comment]
I had actually had this same issue and it was quite sporadic but I did recently narrow it down to a specific job.  That job had a branch of logic that it hit occasionally that was not calling jobCallBack, so eventually it filled up my worker (though utilization showed 0, I am assuming because all jobs had been done or failed, the queue did show true for full though).  I created a simple function to call and report these values: 

    checkQueue = (queue) =>{
       check(queue,String);
       switch(queue){
        case 'process':
            logger.debug(`Queue: ${queue} Current Utility:  ${processWorker.length()}`);
            logger.debug(`Is full: ${processWorker.full()}`);
            break;
        case 'local':
            logger.debug(`Queue: ${queue} Current Utility:  ${localWorker.length()}`);
            logger.debug(`Is full: ${localWorker.full()}`);
            break;
        case 'remote':
            logger.debug(`Queue: ${queue} Current Utility:  ${remoteWorker.length()}`);
            logger.debug(`Is full: ${remoteWorker.full()}`);
            break;
       }
    }

I am using Meteor so I added it as a method and can call it from the web console with whichever queue I want to check as a param.

**Comment by vsivsi** [comment]
@Chugot  Very informative! Thanks for sharing your experience with this type of issue!

**Comment by Chugot** [comment]
Glad to share, I actually came here as I was investigating this issue and saw this post, funny timing.  JobCollection FTW, by the way.

**Comment by wallslide** [comment]
Here is the problem worker:
```javascript 
let receivedShopifyOrderQ = ShopifyJobsQueue.processJobs('receivedShopifyOrder', {
  pollInterval: 5000,
  workTimeout: 15000,
}, (job, callback)=> {
  console.log('receivedShopifyOrder start');
  try {
    let {shopifyOrderId} = job.data;
    ShopifyFulfillmentService.loadOrder({shopifyOrderId});
    let shopifyOrder = ShopifyFulfillmentService.getShopifyOrderByFullId({shopifyOrderId});
    if (shopifyOrder.status === 'LOAD_ERROR' && shopifyOrder.loadErrorCode && shopifyOrder.loadErrorCode === 'MISSING_SAASU_INVOICE') {
      job.fail('missing saasu invoice');
    } else if (shopifyOrder && shopifyOrder.status === 'ORDER_LOADED') {
      job.done();
      ShopifyFulfillmentService.loadRiskCreateJob({shopifyOrderId});
    } else {
      job.done();
    }
    console.log('receivedShopifyOrder finish');
  } catch (err) {
    console.log('receivedShopifyOrder fail');
    console.error(err);
    log.error(err);
    job.fail(err.toString());
  }
  callback();
});
```
Maybe I should put `callback()` in a `finally` block?

**Comment by vsivsi** [comment]
What is `log.error()`?  Can that `throw`?  If so, then that's a path out of your worker function that won't call the callback.  Also, if `job.fail()` itself has an error, it will `throw` in the Meteor server environment, unless you provide it with a callback. With fibers, that is the general pattern for async calls, if you provide a callback, the error is provided there, if not, then it will throw.  In general js exceptions can be problematic like this... (one of the strengths of node.js is the `callback(err, result)` convention.  I personally try to minimize use of exceptions for anything except truly fatal errors that can't be recovered from. Because `catching` throws successfully depends on nothing going wrong in the catch logic (unless you wrap the calls in the catch clause within yet another try/catch structure, and try to recover from the error in your recovery logic... Blech.)

**Comment by vsivsi** [comment]
My guess is that under some rare circumstances `log.error()` and/or `job.fail()` are throwing, which unwinds the stack out of the worker function without invoking the callback, borking a worker slot in that `processJobs()` queue. Get enough of those and all of your worker queues are "stuck".

**Comment by vsivsi** [comment]
I just saw he last line of your comment. Yes, I think putting the callback invocation in a `finally` clause should work, because that should run regardless of what happens in the `try` and/or `catch` clauses.

**Comment by wallslide** [comment]
An update. I've found this error in my logs:
```
Exception in Mongo write: TypeError: object is not a function
 at packages/mongo/mongo_driver.js:322:1
 at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
```
Whenever that error is thrown, the workers stop. Unfortunately it doesn't seem to be caught by try/catch statements. I still haven't found the cause, but I'm adding additional checks to my DB-related statements to make sure I'm not passing in a null value somewhere.

**Comment by vsivsi** [comment]
If that error is being thrown within the `job.fail()` in your `catch` clause above, that would explain why it's not being caught.  You should try wrapping that call in another try/catch and log if it fails.

**Comment by vsivsi** [comment]
I have replicated the type of situation in which that error will occur. If you call any mutator method (insert, update, remove) on a Mongo collection and supply a non function object as the callback, that if the exception you will receive. job-collection does not use callbacks for any of its mutator calls on the server (I just checked), so whatever is triggering this must be in your code (or some package you use).

Example server code that will trigger this error:

```js
// Run in server side code 
var coll = new Mongo.Collection("test");
var _id = coll.insert({ "this": "is", "my" : "doc" }, { "not" : "a function" });
```
Logs an exception to the server console:

```
=> App running at: http://localhost:3000/
I20160307-10:58:46.318(-8)?     at packages/mongo/mongo_driver.js:322:1
I20160307-10:58:46.317(-8)? Exception in Mongo write: TypeError: object is not a function
I20160307-10:58:46.318(-8)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
```

Hope that helps you narrow this down.

**Comment by wallslide** [comment]
The error was being caused by a method call in the `ShopifyFulfillmentService.loadOrder({shopifyOrderId});` which is inside of the `try` statement. I tracked it down to a bug in the older version of the `aldeed:collection2` package that I had been using which has since been fixed (https://github.com/aldeed/meteor-collection2/issues/290).  Hopefully that will solve the problem. It sucks that `try/finally` isn't enough to prevent this kind of error.

@vsivsi @Chugot Thank you for all of your help!

**Comment by vsivsi** [comment]
> It sucks that try/finally isn't enough to prevent this kind of error.

Turns out exceptions generally suck as an error handling construct. This has been born out in many languages (e.g. C++, Java and JS) They seem easier at first, but in large programs with many packages they can hide problems and are difficult to implement, control and effectively communicate and reason about!

**Comment by satyavh** [comment]
I actually have the same issue, very frustrating. 
Jobs that fail (via `job.fail()`) get stuck forever. 

The logs show that the job is being restarted (promoted again to ready) but they actually never run again. 

Worse, it also makes new jobs not moving past 'ready' state. 
Only thing that helps - but only sometimes - is restarting server, which makes the jobServer pick up all jobs again.

It's actually so unreliable I'm thinking to drop this package - which is a shame because it used to work very well.

My job is nothing special, but perhaps the `Meteor.call` inside the job is causing issues.

```
postWorker = Jobs.processJobs('post', { pollInterval: 500 }, (job, callback) ->
  try
    res = Meteor.call 'doSomeSyncApiCall', job.data

    unless res.result.status.code is 200
      job.fail()

    try
      res = Meteor.call 'doAnotherSyncApiCall', job.data

      unless res.result.status.code is 200
        job.fail()

      job.done()
      callback()
    catch e
     job.fail(e)

  catch e
    job.fail(e)

)
```

**Comment by Chugot** [comment]
I think you need to call the callback whether the job fails or not or it will not know the job is complete, please do not disparage such a fine package, it is working as spec in this case :).

**Comment by satyavh** [comment]
Thanks a lot, that really explains! Works like charm now.

**Comment by gVolop** [comment]
@vsivsi 
i had same issue.
but after i add try & catch block. and i always call to callback . 
my queue stuck with a running job....
how can i release it from the db? without redeployment?
what can be the reason? and how can i prevent this error in the future?

**Comment by vsivsi** [comment]
If your worker has a stuck queue (due to returning without invoking the callback) the only way to regain that "slot" is to shutdown and restart the worker process. This is just basic node.js async programming. No different that if your were using one of the many methods in the [`async` npm package](http://caolan.github.io/async/):

For example, if use use the `async.filter()` [method](http://caolan.github.io/async/docs.html#filter):

```js
async.filter(['file1','file2','file3'], function(filePath, callback) {
    fs.access(filePath, function(err) {
        callback(null, !err)     // You MUST invoke this callback every time!
    });
}, function(err, results) {      // Or this results function will *never* be invoked
    
});
```

Job collection provides mechanisms for the *server* to recover from bad workers (that crash, or become unavailable due to network faults), namely [the `workTimeout` option to `jc.processJobs()`](https://github.com/vsivsi/meteor-job-collection#jq--jcprocessjobstype-options-worker---anywhere). But there is no way to automatically "revive" a worker that fails to invoke the callback it is passed.

As for your question on how to avoid this... The answer is the same as I give above in this issue. You must code defensively, and handle every exception that may occur, ensuring that every possible path out of your worker function ultimately invokes the callback. If there is even a single tiny rare corner case where a call to the worker function can occur without a matching invocation of the provided callback, then on a busy server, your worker process will eventually become "stuck", this is just the way async programming works.

I hope that helps.

**Comment by gVolop** [comment]
Thanks!

**Comment by gVolop** [comment]
@vsivsi 
i added try & catch block so - no way i finish the callback eithout calling to callback.
but now, my job runs one time, and failed on the next day.
on the logs i can found:
```
            "message": "Job Failed with Fatal Error.",
            "level": "danger"
```
what can cause this failure?

**Comment by vsivsi** [comment]
Please appreciate that it is impossible to productively do "remote debugging" without being able to see the code involved.

**Comment by gVolop** [comment]
ok.

here is my code:
```
Meteor.startup(function(){
  new Job(JobQueue, 'my-job', {})
        .repeat({schedule: JobQueue.later.parse.text("at 6:00 am")})
        .save({cancelRepeats: true})

  var q = JobQueue.processJobs('my-job', {pollInterval: false}, (job, cb) => {
    var res = {};
    try{
       // pull from mongo and looping on the data... 
       //(The code here take me 3 minutes to run on mongo shell)
      job.done(res);
    }
    catch(err){
      res.err = err;
      job.fail(res);
    }
    cb();
  })

  JobQueue.find({type: 'my-job', status: 'ready'})
     .observe(
        {
          added(){
            q.trigger();
          }
        })
});
```

**Comment by vsivsi** [comment]
It looks like some operation inside of your `try` block is throwing an exception, and so the `fail` is being invoked in the `catch` block. You should be able to see the precise error in the failed job document in the JobCollection's MongoDB collection on the server. The job document has an attribute called `failures` which is an array of error objects, one for each time that job instance was run/retried.

**Comment by gVolop** [comment]
in the job document - `failures`
```
err: {}
```

meanwhile i had restart the worker. now the worker didn't get stuck, but jobs never complete! only "cancelled".
what can cancel my job? is there any methodology to cancel jobs in the package code base
```
[
    {
        "time" : ISODate("2017-02-13T14:17:43.667Z"),
        "runId" : null,
        "level" : "info",
        "message" : "Constructed"
    },
    {
        "time" : ISODate("2017-02-13T14:17:43.789Z"),
        "runId" : null,
        "message" : "Job Submitted",
        "level" : "info"
    },
    {
        "time" : ISODate("2017-02-13T14:22:14.219Z"),
        "runId" : null,
        "message" : "Job Cancelled",
        "level" : "warning"
    }
]
```

**Comment by gVolop** [comment]
@vsivsi 
 
i found the issue.. 
in my `try` block:
```
MyCollection.find({}).forEach((record) => {
  ....
})
```
i tried to execute find with empty query. 
this was fine, until my collection grew (5k+ records) and then - when i tried this query - the mongo driver raised an error - 
`Exception in setInterval callback: MongoError: connection 5 to localhost:27017 timed out`
my `catch` block had never catch error, 
this exception handled by mongo drive - and he try to run the query again and again...

at the end - the job failed,
log - 
```
{
    "time" : ISODate("2017-02-15T14:09:41.517Z"),
    "runId" : "3yWZWhfceqp9JuGns",
    "message" : "Job Failed with Fatal Error.",
    "level" : "danger"
}
```
failures - 
```
{
    "err" : "{}",
    "runId" : "3yWZWhfceqp9JuGns"
}
```
and i can see this log on the console - 
JobQueue: Received error from getWork():  { [MongoError: connection 5 to localhost:27017 timed out]
name: 'MongoError',
message: 'connection 5 to localhost:27017 timed out' }
jobDone failed

my solution was - create a mongo stored procedure, and call it from meteor

many thanks for this awesome package! and your live support!!

**Comment by vsivsi** [comment]
@gVolop  Glad you figured it out. It's always something...  Although that MongoDB error indicates that the connection between your server and your MongoDB instance went down, which led to JobCollection failures on the server-side (as would happen...)

**Comment by Sewdn** [comment]
Hi,

I understand it is crucial to call the callback function of `js.processJobs`.

But I'm wondering what happens with a process that is timing out. One can provide a `workTimeout` property when starting job consumption with `js.processJobs`. But as soon as a job is timedout by taking more time to process then provided with `workTimeout`, the job is failed, but the callback is never called and thus the queue jams.

I think the `workTimeout` property might be confusing to users. You can timeout jobs so they fail automatically, but you still have to setup other mechanisms to timeout the job. Not to fail the job, that one is covered, but to call the callback for the async loop of the processJobs routine. If you have the timeout the job anyway, you can easily also fail the job manually...

If there is any other way to unjam a jobQueue that got stuck after jobs timing out, please tell me, because now I stopped using workTimeout because the jobs were being failed correctly but the queue still got stuck.

Thanks!

**Comment by vsivsi** [comment]
The worker function is an async function. You have to eventually invoke the callback. There's no way around this. If `processJobs()` doesn't work for your case, you can always drop to the lower level interface and use `getWork()`.

**Comment by Sewdn** [comment]
Thanks for your feedback!
I understand the importance of calling the callback. But, in that regard, what is the use case of ever using the `workTimeout` property? In every case, you will also need another timeout within the worker that is doing wok for the job, to be able to call the callback so the queue wont get stuck...

`processJobs` works perfectly; we were just struggling with queues that got stuck because processes were timing out and thus failing.

**Comment by vsivsi** [comment]
workTimeout isn't for the worker it is for the server.  The use case is for workers that unrecoverably crash or lose network connectivity.  It allows the server to automatically fail their jobs so that they may be retried on healthy workers.  

Your case, workers stuck in async calls that don't properly timeout, needs a different solution.
