### ISSUE TITLE
Failed for exceeding worker set timeout - blocks worker

### ISSUE THREAD

**Issue by jdmorriso** [vsivsi/meteor-job-collection#164]
Vaughn, I really like the work you have done here, its a great package. Well done.
One question I have is whether the code that checks for jobs that have exceeded their worker set timeout, should (a) mark the job as failed (currently does this) and (b)  delete the job from the _worker array (currently doesn't do this). Since the queue has determined the job has failed, I feel it should also delete the job from the _worker array, allowing the queue to pickup another job. eg currently, if there is a concurrency of 1 and a single job actually fails and times never calling its callback, the queue will not do any more work. This doesnt sound right to me? Can you share your thoughts whether this change is ok and whether you could make it.

Dave

**Comment by vsivsi** [comment]
HI, thanks for your comment.  Let me restate what I think you are saying here just to make sure we are on the same page:

+ Create a bunch of jobs.
+ Set up a `processJobs()` queue to work on them, with a `workTimeout` expiration, and `prefetch` > 1.
+ If a series of job worker processes takes too long, then jobs waiting in the prefetch queue may fail on the server, but remain in the worker's queue
+ When these "failed" jobs try to run, the worker fails because the job `runIds` are no longer valid.

If this is what you are describing, then yes, you've hit upon an interesting potential interaction between `workTimeout` and `prefetch`. However, at first glace, I don't see a bug here. When using `processJobs`, your worker function is *always* responsible for invoking the `callback` function it is provided. It's an async work queue, no different really from if you were using the popular `async` library; so the callback is critical.

Any interaction with the server may fail, due to network errors, concurrent accesses, etc. Your worker code needs to be defense and handle all possible errors, there's really no way around that.

For example, even if I took your suggestion and automated removal of "auto-failed" jobs in the `processJobs` prefetch queue, that wouldn't save your worker from having to handle the cancellation of jobs on the server, either after they are prefetched into the queue, or even once the worker function has been called and is working. In short, worker code needs to be robust to the server-side invalidation of the job it is currently working on.

Also, the whole point of the prefetch queue is to reduce latency. From a latency perspective, adding a check to ensure that a job is still valid before invoking the worker function would be essentially equivalent to not using a prefetch queue at all! And it wouldn't really solve the problem, because there will always be a race condition between the validity check and the worker starting work (the job could be cancelled, auto-failed, etc. on the server before the worker can communicate any status or results.)

So, unless I'm missing something from you description, it sounds like you are describing the correct behavior of the inherently concurrent nature of the system.

**Comment by jdmorriso** [comment]
Thanks for the quick and detailed response. It has clarified things in my mind and helps me better understand the importance of the worker function to be (i) rock solid to everything (ii) ensure it always calls the `callback` function and (iii) be robust from server side invalidation of jobs.  Great stuff.
