### ISSUE TITLE
QOS style with priorities job processing - maybe Aging?

### ISSUE THREAD

**Issue by gVolop** [vsivsi/meteor-job-collection#205]
@vsivsi, hi! 

i have many types of out http requests, and i put them all in one queue.
but some of them i'll give an high priority of the others.

what will be if i have a case with many jobs from first priority? this will completely blocks all the others jobs until they all completed?

or anyway the others priorities will be handled in some time periods (or another way..)
maybe aging options?
[wikipedia-aging](https://en.wikipedia.org/wiki/Aging_(scheduling))
**Aging is used to gradually increase the priority of a task, based on its waiting time in the ready queue**
Many thanks for the awesome package!

**Comment by vsivsi** [comment]
Hi, job-collection has a relatively simple priority scheme, and aging as you describe is not implemented (because there are many such possible schemes, and covering all possible use-cases would be complex and probably ultimately infeasible). 

However, the beauty of job-collection is that many such custom tasks can be added to the system by simply creating a job to implement them.

It should be straightforward for you to implement your own custom aging scheme by creating a repeating job on the server that queries for other jobs that meet some criteria you define, and then promotes them to higher priorities by pausing each job, changing its priority, and then saving the changes.

**Comment by gVolop** [comment]
yes. i thought about this solution.
but if we can add a QOS functionality into Job-collection it can be awesome.
just to continue to give service also for low level's jobs even we have a many high priority jobs.
so after X jobs from high priority - processing one job from the lower (just let the programer to configure the frequency)

i thought about it for case i have some jobs that do same work, but with other parameters. so i want to give them another priority...
but Okay, i export each of them to another queue, and i use one function as worker.
 and rather than use priority i just configure the concurrency..

**Comment by gVolop** [comment]
ok. you are right. and that was the solution i started yesterday. trying to play with existing rules and options to get my purpose

thanks a lot!
