### ISSUE TITLE
.fail() doesn't support complex payload

### ISSUE THREAD

**Issue by mitar** [vsivsi/meteor-job-collection#23]
While you can pass arbitrary data to `.done()`, you cannot pass it to `.fail()`. Allowing only string message is problematic: I would like to store whole stacktrace, for example. Wouldn't it be useful to have at least a standardized way to store a stacktrace along the message (array of lines)? Or allow storing arbitrary data in the same way as `.done()`?

**Comment by vsivsi** [comment]
Fixed!

**Comment by vsivsi** [comment]
I've also added functionality to `job.fail()` so that it always adds the `runId` to the failure object before writing it to the job document.  This addresses the issue of not knowing which failures correspond to which runs (although it *could* previously be reconstructed from the order in the failure array and the order of failures in the log, these are now more tightly connected).

Also, per your request, `job.log()` now has a `data` option that will store an arbitrary object in the log entry. This is not used for failures however.

These changes are currently on their own branch, but I plan to merge them into `dev` soon.
https://github.com/vsivsi/meteor-job-collection/tree/new_log_failure_data

**Comment by mitar** [comment]
Hm, could you make also `job.fail()` accept data payload?

**Comment by vsivsi** [comment]
Isn't the fail object a data payload?

**Comment by mitar** [comment]
Ah, now I see. You store failure data payload under `failures`, and then you store `runId` there so that it can be matched with the log. Hm, OK. But this makes it complicated to display the log for a particular job. I do not understand why `failures` is not just a counter/number, and you store the `err` object as `data` inside `log` array? Then all log entries would have the same structure, `time`, `message`, and optional `data` payload.

**Comment by vsivsi** [comment]
At this point I'd really prefer not to break the document model. And changing `failures` to a counter would do that. job.fail() could write the failure object to *both* places (failures and log.data) but that seems really wasteful. My intent for the `log` array was always to be something that could easily be made human readable. Whereas the failures data need not be. Now with the optional log.data field, job.log calls can support custom extensions.  The job.fail() failure objects can already do that.

Basically, I think it's suboptimal to force someone to filter through all of the log entries to find the failures. 

I think all of this confusion was seeded by my early decision to automatically write special "success" and "failure" log entries during `job.done()` and `job.fail()` calls. I probably mostly did this for myself as a convenience for not having to write a separate `job.log()` for these events, although doing it in one call/update is more efficient. Note I didn't do it for `job.progress()` however, because there may be a lot of progress calls for a long running job!

Part of me wants to remove the "automatic" `job.done()` and `job.fail()` log entries, simply because they are an undocumented "surprise feature" that is not part of the document model. They don't hurt anything until someone relies on them being a certain way, and then things can break. Which is why I still think of the `log` as a human readable thing, mostly.

**Comment by mitar** [comment]
> job.fail() could write the failure object to both places (failures and log.data) but that seems really wasteful.

I agree.

> My intent for the log array was always to be something that could easily be made human readable. Whereas the failures data need not be.

That's why there is `message` and `data`. ;-)

> At this point I'd really prefer not to break the document model. And changing failures to a counter would do that.

I know that. But this why it is the last chance to break things before the 1.0 release. ;-)

**Comment by mitar** [comment]
Anyway,  I know how to wrap things for myself here around it. I just find it a bit cumbersome. I see that this should be simple one log for everything, and then you can have inside various types of log messages. Automatic message, custom message, failures, successes. And each log message could have both human readable and machine readable part.

But this is only my view. It is your decision. It is good enough for me how it is now.

**Comment by vsivsi** [comment]
I personally like having the result/failures data objects be top level attributes in the job document. Storing them in the log adds a level of redirection, and I'd prefer not to sift through a log that may contain a lot of things to find these really important data.  I'm going to keep the "automatic" log entries for save/rerun/fail/done for now. but leave them undocumented.

**Comment by mitar** [comment]
OK.

**Comment by mitar** [comment]
Probably at some point it will be necessary to support customization of messages for those automatic log messages. At least translation to other languages comes to mind.

**Comment by vsivsi** [comment]
Yet another reason to remove them!

**Comment by mitar** [comment]
What about then create `_logJobFailure` noop method, which does not do anything, but it is called automatically on failure. And `_logJobDone` which is the same. And start? Or what other cases you have when you log?

And then I can extend the class and make it log in the way it is currently logging, or with a translated string. Or whatever? So then log would be by itself always empty. Only `failures` would be populated automatically. And one can then easily extend.

Or maybe it would be even better to create generic hooks. `_onJobFailure`, `_onJobDone`, etc.

**Comment by vsivsi** [comment]
I'm looking at this now.

**Comment by vsivsi** [comment]
@mitar  Your wish is my command.  https://github.com/vsivsi/meteor-job-collection/commit/e19b2c3b8d54d75821c7cd7a4c564e0ddd0628b9

Feedback welcomed.

**Comment by mitar** [comment]
That looks amazing. Even better than I imagined!

**Comment by mitar** [comment]
And this also plays well with stuff from `new_log_failure_data` branch, no?

**Comment by mitar** [comment]
I have nothing more to add. :-) If you will ever be around Berkeley, tell me and I am buying you a lunch. :-)

**Comment by vsivsi** [comment]
Merged into master.
