### ISSUE TITLE
save should fail if cancelRepeats is set to true for forever repeated job and canceling fails

### ISSUE THREAD

**Issue by mitar** [vsivsi/meteor-job-collection#30]
If I have a forever repeated job and it is not in a cancellable state (for example, it is just running), I would prefer that saving fails instead of me having two equal jobs in the queue. So I think that it is better that: if it is cancellable, it cancels, and creates a new one. If it is not cancellable, it fails and keeps the old one.

**Comment by vsivsi** [comment]
This a good idea, I'm looking now into how to implement it.  The wrinkle is I need to make sure that we don't swap the possibility of two jobs running for the possibility of no jobs running.

**Comment by vsivsi** [comment]
Actually, the only states that can't be cancelled are: `cancelled`, `completed` and `failed`.  So I'm not sure I see the issue here. The `cancelled` state is obviously fine, and the `completed` and `failed` cases should also be okay, since `completed` jobs are historical unless manually rerun, and the `failed` cases won't try again unless manually retried.  

So all of the "non-cancellable" states are states when the both won't run again on its own anyway.

> for example, it is just running

Running jobs *can* be cancelled. The worker will continue running, until any call to `job.log`, `job.progress`, `job.done` or `job.fail`, which will fail notifying the worker to stop.

So unless I'm missing something here, there should be no issue to resolve.

**Comment by mitar** [comment]
After more thought, I agree with you. I think I confused something here. Great then that it already works.
