### ISSUE TITLE
getWork should somehow inform the caller when there is work but there was a race condition

### ISSUE THREAD

**Issue by mitar** [vsivsi/meteor-job-collection#41]
Currently, `getWork` prints a warning `Missing running job` and returns an empty list, if there was work, but some other worker took the job before. This is problematic, because caller then doesn't know that it should retry to get more work. It could go then to sleep and worker will be idle unnecessary. (In my case I am fetching only one by one job in each worker from the queue.)

I see two options:
* it could return something like `null` in such case
* it could throw an exception

BTW, in find after update code does not check if number of found documents is the same as number of jobs marked as running. It only checks if there was at least one job returned. I am not sure what would be the best semantics here, but just saying that those edge cases might have to be rethought.

**Comment by vsivsi** [comment]
@mitar  Thanks for your patience. I'm working on this tonight and will report back with what I come up with.

**Comment by mitar** [comment]
No problem. I will also be around, if you will need any help. And then I can put my code into the package and we can have an observe-based implementation as well.

**Comment by vsivsi** [comment]
Okay, at long last, I think I've figured out how I'd like to handle this issue.  Tonight I'm going to prototype a new option to `getWork` that will cause it to automatically retry when it detects the *"Missing running job"* race condition. This way, if there are and matching work items available in the queue, they are guaranteed to be returned by an outstanding getWork request, regardless of whether a race condition is encountered on any given request. 

This should eliminate the need for an exception or special return code to handle this case, and should be even more efficient, because it prevents the otherwise needed additional worker method call round trip to try again. Instead the retry will occur internally in the getWork implementation. If I'm completely satisfied with this new behavior, I may even make it the default, so that devs don't even need to be aware of this case.

Stay tuned.

**Comment by mitar** [comment]
+1

**Comment by vsivsi** [comment]
Okay, I've implemented this on the `master` branch.  You should try it out and let me know if that solves your issue.  No changes in your code should be necessary, you just shouldn't see any more "Missing running job" cases

**Comment by mitar** [comment]
Cool. It is not a common that this happens, so I will just assume it works and open a bug report if we notice issues later.

**Comment by vsivsi** [comment]
Closing...
