### ISSUE TITLE
Can't use transform to modify client side job objects

### ISSUE THREAD

**Issue by maxkferg** [vsivsi/meteor-job-collection#55]
The accepted way to add methods ect to collection objects is to use the transform option when defining a collection. However, the transform function never gets run with Job-Collection objects

```javascript
Jobs = new JobCollection('Jobs',{
	transform:function(){
		alert('I never get called');
	}
});  
```

**Comment by vsivsi** [comment]
This was an oversight / bug. It will be fixed in the next release v0.0.19

**Comment by vsivsi** [comment]
I just committed this to master, and it will be in the next release.  However, for security and robustness reasons, job-collection does A LOT of stringent document verification behind the scenes.  So if you use transform, or otherwise modify jC documents server-side, you will probably get validation errors.

There are currently two ways around this. One is that the server can put anything it wants in a subdocument called `_private`. This is ignored by the validation code, and automatically stripped out of job documents returned to workers.  The other mechanism is that you can create a method on the jobCollection object called `jc.scrub` that takes a job document and removes whatever things you have added to it, so that it will become a valid job collection document again. Essentially it's an "untransform" function.  

You can read more about the current state of things here: https://github.com/vsivsi/meteor-job-collection/issues/20

**Comment by vsivsi** [comment]
And I just noticed that you are talking about "client side" here. In that case, things should "just work" so long as you don't run `makeJob()` on a transformed job, and then try to use it as a job object to interact with the server. I you need to do that, you will probably need to write your own code to scrub the transformations out of the object before running makeJob().
