### ISSUE TITLE
Indexes by default

### ISSUE THREAD

**Issue by chmac** [vsivsi/meteor-job-collection#57]
Let me start by saying thanks for releasing awesome software. You saved me many hours of work doing a much worse job of trying to implement something akin to meteor-job-collection. Really, thanks.

We run a job every minute (every 57s actually, but who's counting...) and we're now up to 8'800 documents in our job collection. On an ec2 m3.medium instance meteor was consuming 100% CPU all the time after 4 days of operation. Once I added the indexes recommended in the readme, CPU load dropped over 50%.

I read vsivsi/meteor-job#3 and I see that #18 was added here. I'd like to suggest that the indexes are added by default. Is there any disadvantage to adding this index? Could it harm performance or increase disk usage under any circumstances?

If there's no downside, I'd like to propose that the indexes are enabled by default. In my case, I had no idea why the server was bogging down so hard, and it took a while to track down the cause. Ultimately I found the index documentation by chance on Google. I think if future users of the package could be saved that without any downside, it makes sense to do so.

If you're open to the idea and would like a pull request, just let me know, I'll try to find a clean solution.

Through this process I learned a lot about Mongo and how to debug it, no doubt knowledge that will come in handy many times over. Again, thanks for the code, really useful.

**Comment by vsivsi** [comment]
Hi, I'm just recently back from vacation. Thanks for this question and for the other work you've done on other topics. I'll start working on these tomorrow. Thanks for your patience!

**Comment by vsivsi** [comment]
Hi @chmac, thanks for your patience. Yes, if you need 8000+ documents in any MongoDB collection, you will need indexes if your want reasonable performance. In general, Meteor kind of glosses over this and assumes you know MongoDB well enough to think of this, which isn't a very "Meteor" way to approach things IMO.

I see you noticed https://github.com/vsivsi/meteor-job-collection/issues/18, and the text that was added to the README in response is here: https://github.com/vsivsi/meteor-job-collection#performance

When this came up last time, the (admittedly limited) consensus was to document the performance implications and then "leave it up to the developer." I think the reasoning for this is that how to best index collections in a database for a given application should be a developer issue. Doing it automatically for the common case won't solve performance issues that then come up when different type of queries are needed for an application with large collections.

I'm leaning towards continuing to force the developer to become aware of this and make explicit indexing decisions by default, rather than hiding the issue until such time as some set of default indexes are not adequate (which admittedly may never happen for some applications...) 

I guess my question for you is: was the Performance note in the README confusing or not prominent enough? I don't want others to repeat the wasted effort that you (and the author of the original issue) went through. 

Another question is: does your application require you to keep all of those job docs around in the collection after they've successfully completed?  job-collection has pretty powerful logging capabilities, and it's easy to write a server-side "reaper" job that runs occasionally and removes old completed jobs that are no longer needed in the collection.  If you do need to keep the historical jobs, the reaper could also insert such old jobs into a separate "history" collection, so the active job-collection stays lean and mean.  You'll still need indexes of course, but at a job per minute, that collection is going to get pretty huge as the months roll by.

Anyway let me know your thoughts. I'm not dead set against setting up some indexes by default, but I still think I'd prefer not to for the reasons stated above.

**Comment by chmac** [comment]
I'm lazy. Maybe not fair to assume all developers are, but Meteor is all about making things easy. I didn't read the point about indexes, and if I did, I skipped over it assuming that our usage (one job per minute) would never reach anything like "performance" issues. In fact, it took me a while to figure out why the server was at 100% CPU once our machine became almost unresponsive.

My guess is that many users, maybe 80%, will not need any indexes. Then maybe another 19% will be fine with the default indexes. Perhaps 1% or less will need more specific indexes than the default. In my opinion, better to deliver an out of the box solution for 99%, and mention in the readme that devs may want to look at the indexes themselves.

My thinking is like this. The default indexes will never **harm** performance. If they help 99% of use cases, then why not ship them by default. Even if they actually only help 19% of use cases, I'd still ship them by default because there is no downside.

I think that once a developer overruns the performance level achievable with the default indexes, they're already at sufficient scale that they'll have many other issues to deal with, and so indexes will be essential. We're running a prototype, with a one minute cron job, and our server stopped working because mongod was consuming all available CPU. I completely accept that it's our responsibility for not reading the README, and I'm incredibly grateful that I only had to add an index, not write a whole job queue.

Our application definitely doesn't require all the job history. We could definitely clean that up. But doing that would mean spending more than two minutes looking into exactly what the cleanup job should do, how it should work, and so on. In this project at least, we're doing everything as quickly as possible. It's a prototype, and we just need it functional for a few months. In my opinion, that's meteor's real sweet spot. Build and prototype ultra fast. Replace if you need real scale or performance. In that sense, I feel like indexes by default would be closer to the meteor way, even if meteor doesn't do much about indexes on its own collections.

Thanks again for the package, it's been really, really helpful.

**Comment by vsivsi** [comment]
Okay, I'm convinced. I'll add the default indexes and modify the performance note in the README to document that and remind developers that they may need additional indexes depending on their application's requirements.  Thanks for reporting your experiences and I'm glad to hear JC has been useful for your project. I'll be pushing a release (v0.0.19) before early next week, and I'll get this into it.

**Comment by vsivsi** [comment]
Oops, Didn't mean to close it... Leaving open until code is released.

**Comment by chmac** [comment]
Awesome, thanks. :-)

**Comment by vsivsi** [comment]
Just committed to master, will be in next release

**Comment by vsivsi** [comment]
Closing

**Comment by vsivsi** [comment]
Also:
https://github.com/vsivsi/meteor-job/issues/3
