### ISSUE TITLE
Connecting Meteor-based worker to collection in another app

### ISSUE THREAD

**Issue by rhyslbw** [vsivsi/meteor-job-collection#59]
What's the best approach to connecting workers to a queue in a different Meteor app? I'm wanting to separate the responsibilities without moving the workers out of the Meteor environment.

**Comment by vsivsi** [comment]
Hi, thanks for your question.  I haven't tried to do exactly this, but it should be pretty easy.  It's very similar to what you need to do when connecting a pure node.js worker to a Meteor server. 

First, you need to make an authenticated DDP connection from the Meteor server hosting the worker(s) to the server hosting the JobCollection, using the [Meteor DDP.connect method](http://docs.meteor.com/#/full/ddp_connect)

Then you can set Job.ddp_apply to the apply method of the returned connection object. 

So something like this:

```js

ddp = DDP.connect( ... );
Job.ddp_apply = ddp.apply

```
You can then use the Job API of the [meteor-job](https://github.com/vsivsi/meteor-job) package to setup workers. 

I this should work, even though I haven't really considered this case too carefully up to now. It uses the undocumented internal Job.ddp_apply, where Job.setDDP should probably work, but currently won't in this case. 

I'm curious what your use case is for hosting workers in a second Meteor server environment, rather than a pure node.js app.  Please share if you can so I can understand what you're trying to accomplish.

**Comment by vsivsi** [comment]
In addition, it should be possible to declare a Job Collection on the "worker server" and then use the DDP connection object to subscribe to the remote server's Job Collection (just as you might do with client code).  You will currently still need to use the `Job.ddp_apply` trick to point the subscribed Job Collection's internal method calls to the remote server's Job Collection however.

**Comment by vsivsi** [comment]
Hi, I've been looking into this a bit more today, and my suggestion in the above comment won't work with released versions of job-collection. The simpler method in my initial comment above should work however.

I'm working on some changes to make this a supported feature.  ou can see the changes I'm trying out in the `new_ddp_handling` branch if you're interested.  Generalizing support for access to remote job-collections has been on my back burner for awhile, and so your initial question has induced me to get this officially supported in the 1.0 release of job-collection.  I'll keep you posted.

**Comment by rhyslbw** [comment]
Awesome, thanks so much. My particular use case is related to scaling of processor intensive file tasks, specifically performing an insert on an [FS.Collection](https://github.com/CollectionFS/Meteor-CollectionFS) with a server path. I'm really just testing all options, as Ideally the queuing and background processing wants to be integrated into FS.Collection, but while the project is in flux, I'm hoping to have jc workers pick up a path one at a time from the queue for an outside in approach.

I'll report back with some results

**Comment by vsivsi** [comment]
Not to plug my own projects too heavily, but if you are using gridFS for your backing store, you should check out [file-collection](https://github.com/vsivsi/meteor-file-collection) if you haven't already.

**Comment by rhyslbw** [comment]
I did review it a while back, but I'm mainly using Amazon S3 and the local filesystem store. It does look like a good project for GridFS only apps though

**Comment by vsivsi** [comment]
Another wrinkle I'm encountering is that Meteor doesn't seem to directly support authenticating with a remote non-default Meteor server via a DDP connection.   

So, for example, I can't seem to find any way to write code for a Meteor server that uses `DDP.connect()` to connect with another Meteor server, and then calls methods on that remote server as an authenticated user.  If there's no way to do this, then that sucks because it means that all such accesses need to either use a custom authentication mechanism, or the remote server needs to run wide-open as far as making those method calls is concerned. And of course this would undermine job-collection and its ability to control access for both Meteor servers and clients when using connections initiated with `DDP.connect()`

This is a solved problem for node.js workers due to the existence of the [DDP-login](https://github.com/vsivsi/ddp-login) npm package (another of my projects).  I suppose I could port a version of that to work within Meteor, but that seems redundant.

**Comment by rhyslbw** [comment]
Right, yes that's where I got up to now you mention it. This issue sounds vaguely familiar, and may already have open issues and/or PR with meteor core. I'll do some investigation

**Comment by vsivsi** [comment]
Great, please let me know what you find.

**Comment by rhyslbw** [comment]
http://stackoverflow.com/questions/16729992/authenticating-with-meteor-via-ddp-and-srp/18645131#18645131

**Comment by rhyslbw** [comment]
Does this work with a corresponding 'login' Meteor.method?

remote = DDP.connect(url);
authenticatedRemote = remote.call('login', {loginCreds}, cb);

http://stackoverflow.com/questions/19830075/login-user-with-ddp-connect-in-meteor

**Comment by vsivsi** [comment]
Right, that makes sense. So long as the two servers are on the same private subnet, (or if you connect using SSL) then doing plaintext authentication is pretty straightforward.  The SRP examples in the first link you sent are obsolete because SRP was retired in Meteor 0.8.2 and replaced with bcrypt on the server-side and SHA265 hashed passwords for the interchange.

**Comment by vsivsi** [comment]
If you want to do the SHA256 method, you can find code to replicate it here:  https://github.com/vsivsi/ddp-login/blob/master/src/index.coffee#L68

It requires access to the node.js `crypto` standard library though, or some alternative such as jparker:crypto-sha256

**Comment by vsivsi** [comment]
Looks like meteor exposes its internal sha package as well: https://atmospherejs.com/meteor/sha

**Comment by vsivsi** [comment]
So putting it all together, if you do `meteor add sha`, then the following should work:

```js
remote = DDP.connect(url);
authenticatedRemote = remote.call('login', {
   user: user,
   password: {digest: SHA256(password), algorithm: 'sha-256' }
});
```

If you're not on a private subnet you should still use SSL because this can be replayed by MitM observer, but it's a little better than just sending passwords in the clear.

**Comment by vsivsi** [comment]
If you want to live dangerously, the plaintext password version of the above is just:

```js
remote = DDP.connect(url);
result = remote.call('login', { user: user,  password: password });
// remote is now authenticated as user
```

**Comment by vsivsi** [comment]
So if you want to try out the new support I added, something like the following should work when using the `new_ddp_handling` branch of job-collection

```js
///////////////////
// Queue Server
if (Meteor.isServer) {

  var myJobs = JobCollection('myJobQueue');
  myJobs.allow({
    // Grant full permission to any authenticated user
    admin: function (userId, method, params) {
      return (userId ? true : false);
    }
  });

  Meteor.startup(function () {
    // Normal Meteor publish call, the server always
    // controls what each client can see
    Meteor.publish('allJobs', function () {
      return myJobs.find({});
    });

    // Start the myJobs queue running
    return myJobs.startJobs();
  });
}
```
```js
///////////////////
// Worker Server

var ddpRemote = DDP.connect(myURL);
var result = ddpRemote.call('login', { user: user,  password: password }); // Or SHA256 method
var myJobs = JobCollection('myJobQueue', { ddp: ddpRemote });
Meteor.subscribe('allJobs');

// myJobs should now work exactly as it would on a Meteor client, e.g.
var workers = Job.processJobs('myJobQueue', 'jobType',
      function (job, cb) {
        // Do the work...
        job.done();
        cb();
      }
);
```

**Comment by rhyslbw** [comment]
:+1: I'll test it out now, looks great

**Comment by vsivsi** [comment]
Just fixed the `Meteor.subscribe()` to be `ddpRemote.subscribe()` in the worker code.  The publish/subscribe isn't necessary unless you want the worker to actually monitor the job queue and act on it.  Although in that case, you can dispense with declaring the worker job collection altogether and just use the `Job` API for the worker:

```js
///////////////////
// Worker Server

var ddpRemote = DDP.connect(myURL);
var result = ddpRemote.call('login', { user: user,  password: password }); // Or SHA256 method

// myJobs should now work exactly as it would on a Meteor client, e.g.
var workers = Job.processJobs('myJobQueue', 'jobType',
  function (job, cb) {
    // Do the work...
    job.done();
    cb();
  }
);
```

**Comment by rhyslbw** [comment]
### Job API
I have a basic collection server, and then a worker in a separate app as outlined in this [Gist](https://gist.github.com/rhyslbw/647e112aa26cee876b22). I'm getting errors on the worker, in particular  Error: Bad ddp object in Job.setDDP(), which looking at the source there is a comment:

> This needs to be called when not running in Meteor to use the local DDP connection.

Doesn't the remote call actually have to run inside a Meteor.startup block as the authentication call omits a callback? Wrapping the worker in a startup block eliminates this problem, but I'm still getting the `bad ddp object` error. 

Logging `ddpRemote` and the value of `result` to the console shows the expected return values.

**Comment by vsivsi** [comment]
Hi, sorry for letting this drop, I've been dealing with a hospitalized family member for a couple of weeks, and am just now getting caught up with things.  I left a question on your gist linked above.  But I think I get it now.  I'm in the middle of adding support for this, so unless you are running on the correct branch of job-collection, what you are trying to do probably won't work yet.  

I'm hoping to release job-collection v1.0.0 tomorrow, and I'd like to get this in, but I need to be able to test it out, and doing multi-server testing is a pain (and not something I personally do for my actual working using this...)

**Comment by rhyslbw** [comment]
no worries @vsivsi , hope all is well.

I've update the [gist](https://gist.github.com/rhyslbw/647e112aa26cee876b22) to better represent the scenario. I can confirm I'm running on the `new_ddp_handling` branch too.

I'm also currently digging into [meteorhacks:cluster)[https://github.com/meteorhacks/cluster], which may be a good option to keep the concerns separate for the scenario of splitting the job collection server and workers into separate apps, particularly for authentication ([Cluster-wide authentication](https://github.com/meteorhacks/cluster/issues/14)) and service management.

**Comment by vsivsi** [comment]
Hi @rhyslbw,  I've fixed the bug that was causing the "Error: Bad ddp object in Job.setDDP()" you were seeing above.  It is committed on the `dev` branch.  I've also added unit tests for this functionality that utilize the Meteor client side to test this out.  Everything looks good to me now.  If you get a chance, can you please checkout the `dev` branch and make sure that it fixes the issues you were seeing?  Thanks -V

**Comment by rhyslbw** [comment]
I've started testing, but have to turn in for the night. Looking good so far!

**Comment by rhyslbw** [comment]
Tick this one off, great job. I'm still trying to get to the bottom of a separate problem I'm having with the dev branch, but have confirmed this is working as expected.

**Comment by rhyslbw** [comment]
The other problem wasn't an issue with the dev branch, and it's all working as expected

**Comment by vsivsi** [comment]
Great, thanks for the feedback.

**Comment by rhyslbw** [comment]
Hmm, I'm now having a few problems related to the remote connection, so ran the test suite on a fresh clone of the repo, with the dev branch for both job-collection and job checked out. It's failing on the client-side `Run startJobServer on new job collection` with 

    - fail - error 404 - reason Method not found - message Method not found [404] - errorType Meteor.Error - constructor [object Object] - clone Error: [undefined]

**Comment by vsivsi** [comment]
Are you waiting on `Meteor.startup()` before making the call?  Method calls from a client will return 404 if the server hasn't completely started (collection isn't running, methods haven't been defined).

**Comment by rhyslbw** [comment]
I'll take a look at my code, but the error I posted above is just the test suite failing in a new default app

**Comment by vsivsi** [comment]
Your test suite, or the built in unit tests?

**Comment by rhyslbw** [comment]
Sorry, the built in suite on the dev branch

**Comment by vsivsi** [comment]
Hmmm, okay, I'll try hiss gain myself and see if I can replicate it.

**Comment by rhyslbw** [comment]
The problem I'm having is when calling .done() in a server-only worker function running in a separate Meteor app. I'm triggering via an observe for added documents on the Job Collection. In addition to the remote ddp server, I'm also connecting to a different Mongo Database by passing options._driver property to the JobCollection constructor, which all works fine, but I have tested without this extra complexity, and it's the same result.

`Exception while simulating the effect of invoking 'queueJobs_jobDone' [Error: Can't call yield in a noYieldsAllowed block!] Error: Can't call yield in a noYieldsAllowed block!`

This is the job object as logged to the console:

    { root: 'queueJobs',
   _doc:
    { _id: 'sxb7trK28r8cwdqAu',
      runId: '5Bd7kAKMGb55FqaFh',
      type: 'insertImage',
      data:
       { job: [Object],
         path: '/testImport2/20090313-125012-00630.JPG' },
      status: 'running',
      updated: Sat Mar 14 2015 21:40:03 GMT+1100 (AEDT),
      created: Sat Mar 14 2015 21:36:52 GMT+1100 (AEDT),
      priority: 0,
      retries: 9007199254740991,
      retryWait: 0,
      retried: 1,
      retryBackoff: 'constant',
      retryUntil: Sat Sep 13 275760 10:00:00 GMT+1000 (AEST),
      repeats: 0,
      repeatWait: 300000,
      repeated: 0,
      repeatUntil: Sat Sep 13 275760 10:00:00 GMT+1000 (AEST),
      after: Sat Mar 14 2015 21:36:52 GMT+1100 (AEDT),
      progress: { completed: 0, total: 1, percent: 0 },
      depends: [],
      resolved: [] },
   _taskId: 'Task_0' }

**Comment by rhyslbw** [comment]
In development I'm not using the built in Meteor Mongo in each app, but am pointing both the apps to the same local Mongo database. When breaking this out into a [sample repo](https://github.com/rhyslbw/jc-remote-worker-observer) the collection in the worker accessing documents from the jc-server app

**Comment by vsivsi** [comment]
Hi, just to let you know that I've been dealing with family issues again for the past few days, so I haven't been able to look into this yet. I'll try to dig into it tonight and see what I can find out.

**Comment by vsivsi** [comment]
Hi, I just tried the unit tests from a fresh clone of job-collection and got no errors (Meteor 1.0.4.1 on OS X 10.10.2):
```
git clone --recursive https://github.com/vsivsi/meteor-job-collection.git jcTest
cd jcTest
git checkout dev
cd job
git checkout dev
cd ..
meteor test-packages ./
```
On server:
```
[[[[[ Tests ]]]]]                             

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
```

On client:
```
All tests pass!  8116 ms  Passed 24 of 24
tinytest
PASS  5 ms  S: JobCollection default constructor
PASS  0 ms  S: Set permissions to allow admin on ClientTest
PASS  6 ms  S: Set polling interval
PASS  4 ms  S: Run startJobServer on new job collection
PASS  32 ms  S: Create a server-side job and see that it is added to the collection and runs
PASS  27 ms  S: Create a job and see that it is added to the collection and runs
PASS  53 ms  S: Dependent jobs run in the correct order
PASS  73 ms  S: Job priority is respected
PASS  532 ms  S: A forever retrying job can be scheduled and run
PASS  1293 ms  S: Retrying job with exponential backoff
PASS  2019 ms  S: A forever retrying job with "until"
PASS  2 ms  S: Run shutdownJobServer on the job collection
PASS  37 ms  C: JobCollection default constructor
PASS  33 ms  C: Run startJobServer on new job collection
PASS  50 ms  C: Create a job and see that it is added to the collection and runs
PASS  84 ms  C: Dependent jobs run in the correct order
PASS  98 ms  C: Job priority is respected
PASS  531 ms  C: A forever retrying job can be scheduled and run
PASS  1036 ms  C: Retrying job with exponential backoff
PASS  2027 ms  C: A forever retrying job with "until"
PASS  8 ms  C: Run shutdownJobServer on the job collection
PASS  12 ms  C: Run startJobServer on remote job collection
PASS  109 ms  C: Create a job and see that it is added to a remote server collection and runs
PASS  45 ms  C: Run shutdownJobServer on remote job collection
```

**Comment by vsivsi** [comment]
@rhyslbw  Hi, okay, you are right, the option needs to be `connection` not `ddp`.  I missed that somehow.  I've changed this everywhere within the code and docs.  This still needs more testing, but hopefully that resolves your continued issues. 

I've updated the `dev` branch with this change.

**Comment by rhyslbw** [comment]
I'll check it out now, thanks! Not sure what's going on with my test runs, I'll try again with the dev branch changes and report back

**Comment by rhyslbw** [comment]
I am still getting the same error I previously reported:

    Error: Can only call _ensureIndex on server collections
    at new JobCollection (packages/vsivsi:job-collection/server.coffee:30:9)

The test suite in it's current form now does pass for me, but it doesn't seem to be covering the scenario. On [line 50](https://github.com/vsivsi/meteor-job-collection/blob/dev/job_collection_tests.coffee#L50), the server-side JobCollection isn't connecting to the remote dpp server. Changing to the following crashes the tests with the same listed above. 

    remoteConnection = DDP.connect 'localhost:3000'
    remoteTestColl = new JobCollection 'RemoteTest', { idGeneration: 'STRING', connection:    remoteConnection }

    if Meteor.isServer
      remoteTestColl.allow
      admin: () -> true
      # remoteTestColl.startJobServer()

**Comment by vsivsi** [comment]
Okay, yes I think I know what is causing this error. I will fix it in a few hours. Thanks for your patience.

**Comment by vsivsi** [comment]
I've committed a fix for this to the `dev` branch.  -V

**Comment by rhyslbw** [comment]
Ok so we are down to the root of the problem now :-).

The methods calls on the job object within the worker function are failing eg `jobDone failed`. I'm working through the job class to see if I can track down anything, but I'll update the demo repo shortly.

**Comment by rhyslbw** [comment]
I've just updated the [demonstration repo](https://github.com/rhyslbw/jc-remote-worker-observer). Readme has details

**Comment by vsivsi** [comment]
I'm looking at this now...

**Comment by vsivsi** [comment]
There appear to be a couple of things going wrong here... The getWork calls in the worker processJobs are failing as Unauthorized because the userId passed to the admin allow function is null. So somehow the authentication isn't working.

The other mystery is why processJobs is calling the worker callback when processJobs fails with a 403.  That is a bug.

You can see all of this by adding this line to the server script just after the new JobCollection:

```js
jc.setLogStream(process.stdout);
```

**Comment by vsivsi** [comment]
Actually, The unauthorized calls were coming because I restarted the server without also restarting the worker, so the initial login token was no longer valid...  In a real app, the login call needs to be put in a call to the function defined for `connection.onReconnect(function () {});` so that server reconnects will properly reauthenticate.

Anyway, that's not the jobDone failed problem...  The weird thing is that jobDone on the server side appears to be returning `true`.

**Comment by vsivsi** [comment]
Okay, here's what it looks like is happening:

The DDP methods are running on both the worker and the server, just like they do when a method call is made on a Meteor client. In the case of a Meteor client, the method call "stub" runs locally and only changes the local minimongo DB; this is part of Meteor's "latency compensation" mechanism. Once the server-side method runs, any DB updates it causes will propagate to the client and replace the client minimongo document. Notably, the server allow/deny permissions don't apply to the client minimongo, and the client doesn't set any allow/deny rules (because it can't be trusted).

So what is different when the "client" worker is actually running in a Meteor server environment? Well, it seems that the `update` in the method that runs on the worker side of the job collection is failing, which leads to the `jobDone failed` message on STDERR. The server side version of the method call is working fine, and the job is indeed being marked as `completed` in the database. 

For some reason the update to a job document on the subscribing side of the collection is failing.  The job document appears to be in the local collection, but the server method stub isn't being allowed to write to it in the same way that a Meteor client method stub can. I'm not sure if this is a bug in Meteor or if I'm just not getting why a remote collection in the server environment is being treated differently than a remote collection on a Meteor client is. Both should be implemented as minimongo collections, and minimongo shouldn't care about allow/deny, because it's not persistent and will soon be updated by the DDP subscription anyway.

I'm note sure how to fix this.  I could hack around it by not executing method stubs on the calling side when the caller is a Meteor server, but that seems pretty lame. Or I could delve into why this behavior differs between Meteor client code and Meteor servers that use a remote collection. 

This probably needs more research into whether this is behavior is intentional in Meteor, or if it is a bug or oversight.

**Comment by vsivsi** [comment]
Just found the answer...  
> When, on the server, you write to a collection which has a specified connection to another server, it sends the corresponding method to the other server and receives the changed values back from it over DDP. Unlike on the client, it does not execute the write locally first. 

I learn something new everyday!

So the updates are failing in the worker stubs because JC specifically denies all remote database changes.  I guess I need to just eliminate the worker side method stubs when the the job collection is remote on a meteor server.  I guess this makes sense, since "latency compensation" is pretty pointless when there is no user interface to update.

This shouldn't be too hard to fix, but it's getting pretty late here, and I'll probably break more things if I do it now.  Thanks for the very clear reproducing case, this would have taken forever to debug without it.

**Comment by rhyslbw** [comment]
I really appreciate your time on this, thanks for the detailed explanation of all the issues. I'm glad this wasn't a shortfall or bug with Meteor, especially since the behaviour makes sense when you consider the point of stubs. It seems like a solid solution can be implemented to fully support remote meteor to meteor jc architecture with the 1.0 release. This is awesome!

I'm happy to keep the demo repo around as a linkable example for documentation purposes after a little refactoring too.

Get a good night sleep, you've earned it :-)

**Comment by vsivsi** [comment]
The fix was trivial, just don't set-up methods for JobCollections on the server when a connection is provided.  It's committed to the dev brnach.

**Comment by rhyslbw** [comment]
Nice, love it when removing code is the right solution. Ok we are done here, again thanks for your time on this. Bring on 1.0!

**Comment by rhyslbw** [comment]
I've updated the [demo repo](https://github.com/rhyslbw/jc-remote-worker-observer). I've added quite a few things to properly demonstrate this setup, including simulation for failures and variable durations. If anything sticks out just submit an issue in that repo
