### ISSUE TITLE
Does this package support workers creating the job and the server doing the processing?

### ISSUE THREAD

**Issue by hanchang** [vsivsi/meteor-job-collection#61]
I have an application where a lot of workers go out and retrieve data in parallel.

After each worker returns, I'd like the server to process the data for many reasons:
1. The computation is slightly expensive; workers are variable cost based on runtime while server costs are fixed monthly, plus the server has better specs than the workers.
2. The computation is complicated and relies on collection hooks that will only fire if the updates happen within the Meteor app; they do not fire when the worker externally modifies the Mongo database.

Does this package support the use case where the worker is the one producing the job, and the server is the one consuming the job?

Thanks in advance!

**Comment by wulfmeister** [comment]
I'm not sure I understand.  Could you be more specific about where your jobs are running?  Is your question just "How do I pass the data I get back from the job (I'm assuming async calls?) to another function in my Meteor app?"  What makes you think you can only modify the db directly instead of modifying a collection (which works just fine in my workers)?

**Comment by vsivsi** [comment]
Hi, yes, remote workers can create new jobs that will run on the server, and they can be made dependent on the completion of the remote job that created them (so they won't run too early).

The workers just need to be authenticated as a user that has permission (via allow/deny rules) to create new jobs.

The entire Job object API can be run anywhere, it just needs to be configured to give the proper permissions. So any Job running in a worker can create new jobs, or remove old jobs, or ???.  It's one reason I haven't built in lots of "housekeeping" functionality (e.g. completed jobs are automatically removed after 5 days...) because it is easy to create repeating jobs that perform such tasks yourself.

**Comment by hanchang** [comment]
Awesome, thanks for the detailed response!
