### ISSUE TITLE
stopped property on client

### ISSUE THREAD

**Issue by rhyslbw** [vsivsi/meteor-job-collection#66]
I'm building out an admin interface for a remote JobCollection server, and would like to have a switch to control the jobServer. I've found the undocumented but public server-only property on the Job Collection object `stopped` that provides the status. Is there a reason this is not available to the client?

**Comment by vsivsi** [comment]
How would you propose to implement that? ` jc.serverStatud()` that bottoms out in a method call?  Or would you want a reactive data source?  The former is easy.  The latter I'm sure is doable, but I'm not exactly sure how best to approach it. Is there an easy way to reatively "remote" a server side variable like that without doing something hacky like stuffing it io a special "non-job" status document in the mongo collection?

**Comment by rhyslbw** [comment]
I'm currently using a method, but ultimately a reactive source would be gold. I'm not too sure about the approach, so will do some research. There are probably other people thinking about this too given the recent interest in splitting apps up into separate responsibilities. I might post on the [Meteor Forums](https://forums.meteor.com/) too.

**Comment by vsivsi** [comment]
Answering my own question... The only good way to make it reactive would be to write a custom publish function in the server that publishes a single document with server status, that automatically sends `changed` updates when the server goes up/down. The client code would need to create another minimongo collection and then subscribe to the server publish. A find on that collection could then be used to keep a session variable up to date. 

The problem with all of that, besides being a lot of heavy lifting for a single bit of information is that it wouldn't work at all with the pure node.js Job API. The method call would (the whole API is built that way) so I'd be inclined to keep it simple and implement it as a method call, but that would mean polling that method if you wanted to keep the status up-to-date. Maybe there's another better solution I'm missing here, but this seems to be a weakness of meteor that all of the client server shared state needs to go through mongo pub/sub in order to exploit reactivity.

**Comment by rhyslbw** [comment]
Right yes, in fact I'm doing exactly this with a package I've written to pick a filesystem path from a remote server. I've create a server-side package that loops through a configuration file to instantiate the publications, and a client-side package that provides the UI (with built in subscription) and logic, including calling the configurable method on submit.

Companion packages may be the better way to wrap this up without polluting the primary codebase, but we can publish the data without using Mongo on the server, just call .added() within the publish function. This should keep implementation within [spec](https://github.com/meteor/meteor/blob/master/packages/ddp/DDP.md) for the node app right?

**Comment by rhyslbw** [comment]
I'm writing an extension that I'll initially run in a package, but once 1.0 drops I'll prepare a PR for consideration in core. I've got a design that I believe is a natural fit with Job-Collection

**Comment by vsivsi** [comment]
FYI I've written a very rudimentary implementation of something along these lines in the new jc playground app here: https://github.com/vsivsi/meteor-job-collection-playground/blob/master/play.coffee#L363-L373

It's built on the new event emitter support
