### ISSUE TITLE
More clarity with naming of makeJob()

### ISSUE THREAD

**Issue by rhyslbw** [vsivsi/meteor-job-collection#67]
[makeJob()](https://github.com/vsivsi/meteor-job/blob/master/src/job_class.coffee#L323) is another ambiguous method name given the presence of [createJob()](https://github.com/vsivsi/meteor-job-collection/blob/master/shared.coffee#L123) in the API. As this is a lower level call, the few extra characters for something like `makeJobFromDoc()` would be a fair trade-off in my mind.

**Comment by vsivsi** [comment]
Seems reasonable. I'll sleep on it and make the change tomorrow, deprecating makeJob()

**Comment by vsivsi** [comment]
Hi, so in the meteor-job npm package, I'd already eliminated this method entirely in preference of just `job = new Job(collectionName, doc);`

This is complicated a bit in job-collection because the Job class really isn't documented for direct use, and because this call needs to know the collection with which to associate the the resulting Job object. 

So this is really just a convenience function that could possibly go away entirely:

```js
job = jc.makeJob(doc);
// versus
job = new Job(jc.root, doc); 
``` 

What do you think, just eliminate `makeJob()` altogether and document the other way?

Same is true for `createJob()` actually, it's just shorthand for:

```js
job = jc.createJob(type, data);
// versus
job = new Job(jc.root, type, data); 
```

IMO, these both of these methods could go and be replaced by better documentation of `new Job()`.

Thoughts?

**Comment by vsivsi** [comment]
Also, the `Job` constructor could easily be enhanced to just directly support:

```js
job = new Job(jc, type, data);
// and 
job = new Job(jc, doc); 
```

**Comment by vsivsi** [comment]
@rhyslbw  I just made the above change to `meteor-job`.  So, here's the choice:

```js
job = jc.makeJobFromDoc(doc);
// versus
job = new Job(jc, doc);

// and

job = jc.createJob(type, data);
// versus
job = new Job(jc, type, data); 
```
I think we should just ditch the two extra methods and improve the documentation of the Job object constructor.

**Comment by rhyslbw** [comment]
Considering makeJob and createJob are no more expressive than new Job, I'd vote for these two to be depreciated. It will help expose to the developer how the job class fits to the collection package. Passing in the jc object is much nicer though, and personally wouldn't make one change without the other

**Comment by rhyslbw** [comment]
Right on. Sorry I didn't see your reply drop in as I was typing my reply. We're on the same page

**Comment by vsivsi** [comment]
Okay, I'll deprecate both makeJob and createJob and I'll add documentation for `new Job(...)`.  It's already documented for meteor-job, so this won't take too long.

**Comment by vsivsi** [comment]
Committed to dev branch.

**Comment by vsivsi** [comment]
Merged into master
