### ISSUE TITLE
Job cancellation callback

### ISSUE THREAD

**Issue by brentjanderson** [vsivsi/meteor-job-collection#70]
Hello,

I'm using job-collection to spread tasks among workers, where each job involves creating objects that are local to the worker that are cleaned up when the job is completed, fails, or cancels. Unfortunately, if a job is cancelled somewhere in the system (on a client or another server node) and that job is currently  running on another worker, I'm not sure how to clean up that job's resources. I could have an observer set that watches for cancelled jobs and performs cleanup at that point, but I'd expect the jobQueue API to support declaring a callback for the cancelled state transition (or perhaps any other transition) that would be triggered by the node processing the work.

Does this sound like a reasonable way to solve this particular issue? I'd anticipate the API could be as simple as:

`jq.registerStateCallback(jobType, stateName, [options], callback)`

Where `jobType` is the type of job, `stateName` is the state transition we wish to capture a discrete event for, `options` for any future needed options (none come to mind at the moment), and `callback` would be passed the `job` object affected.

Is there something like this available already? Otherwise, I'm more than happy to give this a shot and submit a pull request.

**Comment by vsivsi** [comment]
Hi, thanks for your question.

The way I had envisioned for longer running workers to know if the job they are working on has been cancelled/removed is through periodic calls to `job.progress()`, which succeeds and returns `true` only if the job still exists and is in the `'running'` state in the server's Job Collection (and the `runId` still matches!).  If `job.progress()` returns `false` it means that this instance of the job is no longer running and the worker should stop working on it (freeing up any resources, etc.)  If `job.progress()` returns `null`, it means that the server is in the process of being shutdown, and so the worker should either `fail` the job and stop working, or make provision to continue working (if the job is very long running) in hopes that the server will come back online before the job completes.  

This is the mechanism I designed in part because this lower level stuff was done before I even wrote JobQueue and decided to include it in the package. Ideally the way this is all handled needs to work with workers that obtain their jobs via the lower level `jc.getWork()`call.

JobQueue doesn't currently monitor the server status of any running jobs, it's much dumber than that. That is left up to the workers themselves using the `job.progress()` mechanism.  Another reason for it working this way is that JobQueue (and Job) are each implemented as pure node.js code, so there's no Meteor specific code (e.g. minimongo) in them except support for making DDP method calls.

So to implement your suggestion in JobQueue would greatly complicate it, and would be very difficult (though not impossible) to do in a way that maintained that code as a "node.js only" implementation, rather than requiring the full Meteor environment to work.

I hope that all makes sense.

In any case, this could all certainly be documented better...

**Comment by vsivsi** [comment]
I just want to add that the `job.progress()` mechanism is also important/useful to solve the opposite problem... How does the server know when to give-up and "auto-fail" jobs that are supposedly running on remote workers that may have crashed, hung, lost network connectivity, etc.?

Each time a `job.progress()` is received on the server side, it updates a timestamp in the running job, so the developer can implement a server-side "reaper" job that automatically fails jobs in the collection that haven't had progress updates in N-minutes, or whatever policy makes sense for your application. If the jobs are set to automatically retry (or if the "reaper" explicitly fails/restarts them) then that work can be salvaged back from a dead worker to reassign to a new one. This is the purpose for the `runId` on the job, so that the server and worker can correctly handle the case where a job is failed/restarted assuming that the original worker is dead, but then it phones home... That call won't succeed because the `runId` won't match any more (and the worker will get a `false` return value).

**Comment by brentjanderson** [comment]
Excellent - Thank you for the feedback! I will give this a shot and update with feedback if needed.

**Comment by skosch** [comment]
Hm, I see the reasoning, but this is somewhat tricky in my case. My workers spawn computation processes (mathematical optimization) that could run for days, sometimes with hours between `stdout` messages, and often only stop once the user decides that the current result is "good enough". In other words, there isn't a notion of progress as a percentage, and also nothing that would regularly trigger calls to `progress()`. I've tried running dummy `progress()` calls within a `setInterval()` with limited success (the intervals don't seem to fire reliably when the CPU is near 100% busy computing).

What does work, however, is publishing
```javascript
Meteor.publish("jobsProgress", function() {
  if(isWorker(this.userId)) {
    return jobs.find({}, {fields: {progress: 1}});
  }
});
```
and then have the workers subscribe to that and watch those `progress` changes:
```javascript
ddp.observe("allJobs.jobs").changed = function(id, oldFields, clearedFields, newFields) {
  if (newFields.progress && newFields.progress.completed ===  MAGIC_NUMBER) {
    spawnedProcess.stdin.pause(); // I need to allow clients to kill the computation
    spawnedProcess.kill();
  }
};
```
The `progress` is changed by the client to `MAGIC_NUMBER`, and `done()` is called in `spawnedProcess.on('close', ...)`, and everything works out. (I've tried using `cancel` instead of the `progress` hack, but then `done()` doesn't work on non-running jobs so I don't get my precious result back).

Could you comment on any potential downsides (besides the obvious ugliness) to this approach that I may be overlooking?

**Comment by vsivsi** [comment]
@skosch  a couple of quick points:  

Progress is not really a percentage, it's the ratio of two integers and they can both change. It's not even required to monotonically increase. 

Log messages from the worker can contain essentially any data that you want to stuff into them and unlike progress they are permanently recorded in the job document on the server. 

The Worker can update its local job document (even in a plain node.js worker) anytime it wants by calling `job.refresh()`. The server (or a client via a custom method call) can update the job data to include new information and the worker can act on that when it refreshes. Sort of a paupers IPC. The worker can also make custom DDP method calls to obtain status updates or instructions. 

However, as you've discovered, the only way to "push" information out over DDP is with Pub/Sub.
