### ISSUE TITLE
Increasing delay before it runs

### ISSUE THREAD

**Issue by rclai** [vsivsi/meteor-job-collection#74]
If I create a job with a delay of 10 seconds but before those 10 seconds happen I decide to change that delay to 20 seconds instead, will it know to wait 10 more seconds?

**Comment by vsivsi** [comment]
Hi, you can do this.  You need to pause the job, change the delay, save the change and then resume it. 

```js
job.pause()
job.delay(20000)
job.save()
job.resume()
```

The above code will delay 20 more seconds. If you truly want to delay 20 total seconds, the.you'll need to do the math to figure out the new delay value given the amount of time elapsed since the last time the job was saved. 

Once a job has been saved to the server the first time, you have to pause it to change it in any way. Once paused, you can change anything about it using the above steps (except the `jobType`, if you need a new type of job, just create a new job and delete the old one).

**Comment by rclai** [comment]
Okay thanks.
