### ISSUE TITLE
concurrency setting ignored?

### ISSUE THREAD

**Issue by dcusan** [vsivsi/meteor-job-collection#82]
Hey Vaughn, this package is impressive, congrats!
This is more a question than a bug report. We have created several `JobQueues` (aprox. 20) for our job collection `Jobs` through `Jobs.processJobs()`

For most of these JobQueues we have specified a standard options object like so:
```JavaScript
{
    concurrency: 2,
    pollInterval: 5000,
    prefetch: 1
  }
```
However looking at the job collection at any given point, I can see more than 2 jobs of a certain type with status 'running'. Is this normal? I thought the `concurrency` setting limited this. Thank you in advance.

**Comment by vsivsi** [comment]
Hi @dcusan, thanks for the question.  There are two possible explanations if I understand your use case correctly:

1.  The `prefetch` setting can increase the number of apparently running jobs by the amount indicated. So in your case with `concurrency:2, prefetch:1` that allows three jobs in a JobQueue at a time (with up to two with active workers). The third job in the queue is waiting for one of the workers to finish, but in the JobCollection itself it is marked as `'running'` because it is no longer available for another worker to add to its own queue. This feature exists to reduce work request latency across slower network connections. The local worker JobQueues are strictly FIFO when prefetch is in use. Anyway, if this is not desirable behavior in your app, simply set `prefetch: 0`

2.  In your post above you describe having "approximately 20" instantiated JobQueues. I can't tell from your question if those are configured to work on the same or different types of jobs. But if they are configured to work on the same job type(s), then that obviously increases your concurrency as well. Assuming 20 JobQueues working on the same type of job, that configuration could have up to 60 `'running'` jobs at once in the main JobCollection. 

Hope that helps to clear things up!

**Comment by dcusan** [comment]
Thank you for your thorough answer @vsivsi.

The JobQueues are actually all configured on different job types, so that every worker(s) of the queues works on different job types.

Another question right here: Is my understanding right in saying that the amount of local workers spawned depends on the amount of the `concurrency` setting passed to the JobQueue multiplied by the amount of JobQueues?

I followed your recommendation and my settings look like this now for one particular JobQueue:
```JavaScript
{
    concurrency: 1,
    prefetch: 0
}
```
I can still see more than one job with status `running` at a time for that particular job type. Is this still expected behaviour?

Thank you again!

**Comment by vsivsi** [comment]
Hi, if you only have one JobQueue defined for each type of Job with those settings:

```js
jq1 = jc.processJobs('type1', {concurrency: 1,prefetch: 0}, function (jb,cb) { /* type1... */ });
jq2 = jc.processJobs('type2', {concurrency: 1,prefetch: 0}, function (jb,cb) { /* type2... */ });
// ...
```

If this is what your code looks like, then yes, you should only ever have one job *of each type* running at a time. So with the above code, you could have two simultaneous jobs running, one of each type.

If you want only one job of any type to run at a time, you need to do this:

```js
jq = jc.processJobs(['type1','type2'], {concurrency: 1,prefetch: 0}, function (jb,cb) { 
   switch (jb.type) {
      case 'type1': 
         // Work on type 1
         break;
      case 'type2':
         // Work on type 2
         break;
      default:
         throw(new Error ("Bad job type in worker!"));
   }
 });
```

`jc.processJobs()` is just a (powerful) convenience function. It's nothing more than a fancy wrapper 
around `jc.getWork()` which is the underlying primitive operation of turning jobs from ready to running...

One thing to watch out for though is that **every time** you run `jc.processJobs()` you create a new JobQueue that keeps running in the background until you tell it to stop.  So, if code like the above is somehow called multiple times, then that could cause behavior like you describe.

Anyway, you should not be seeing multiple running jobs of the same type, provided only one call to `processJobs()` has been made for each type of job and the concurrency and prefetch settings are `{concurrency: 1, prefetch: 0}`.  If you think you are doing everything correctly and are still seeing this, please reduce it down to a simple minimal test application that produces the bahavior and Id be happy to take a look. Note however that this is a very mature part of this package, and nobody has ever reported something like this, so odds are good that something in your code isn't quite right.

**Comment by vsivsi** [comment]
Oh, and I should add... Make sure that `jc.processJobs()` isn't being run in your ***client*** code.  Clients are perfectly capable of running workers, and of course that would create workers for each client.  Also, if you have multiple servers, each running this code, that could cause it as well...

**Comment by rhyslbw** [comment]
As part of my work [implementing a job-collection to manage worker tasks in CollectionFS](https://github.com/CollectionFS/Meteor-CollectionFS/pull/667) I initially had separate queues configured for each of the tasks, but have since moved to just a [single queue](https://github.com/rhyslbw/Meteor-CollectionFS/blob/feature/jc-queue/packages/job-manager/server.js#L112), with tasks and their associated worker function [registered](https://github.com/rhyslbw/Meteor-CollectionFS/blob/feature/jc-queue/packages/worker/fileWorker.js#L159) in an extensible way. This allows me to set job priorities since there are lower priority jobs that are related to cleanup, and should be done after all the primary work is complete. This is important when batch inserting many files as building a thumbnail is more important than removing a temp file.

It seems like ideally you wouldn't want multiple queues running at the same time right?

**Comment by vsivsi** [comment]
@rhyslbw  Thanks for your input on this issue.  Also, glad to hear that CollectionFS is proceeding on this!

@dcusan  I just thought of another even simpler situation that could lead to multiple `'running'` jobs of the same type in the Job Collection when concurrency is set to 1:

If a worker function receives a job, but then for any reason fails to eventually call `job.done()` or `job.fail()` that job will forever remain in the queue as `running`. For example this often happens in development mode, where you start a server with `meteor`, and internally a worker starts working on a job, and then you hit `^C` and shutdown the meteor server.  That worker will die having never completed/failed that job. In production this can happen when a remote worker has a job and it's network connection drops, or server crashes or whatever.  In my [job-collection sample app](http://jcplayground.meteor.com/), this can happen if someone closes the browser tab/window of their client while it is working on a job.

job-collection doesn't have a built-in automatic mechanism for resolving such situations because the right thing to do seems very app/job specific. But generally what you need to do is write a "reaper" job of some kind that detects these "zombie" running jobs and auto-fails them so they can be retried by another worker.  Here is the code that does that for the sample app: https://github.com/vsivsi/meteor-job-collection-playground/blob/master/play.coffee#L383

**Comment by dcusan** [comment]
Thank you @rhyslbw and @vsivsi for the extensive input. My JobQueues are created exclusively within server code. However I have not been able to reproduce this in a 'fresh' repo, therefore I must be doing something wrong. 

I appreciate the input a lot and consider the question answered. Thank you again!
