### ISSUE TITLE
Keeping the latest _id of a repeated job

### ISSUE THREAD

**Issue by tcastelli** [vsivsi/meteor-job-collection#92]
Hi there, been using this for a while, and while it works mostly great( i also feel like autokilling for zombies would be great :P) I have a question about how could I keep track of the latest "cloned" job id (after a job.done() with repeat).
The thing is that when the job is firstly created i keep the id on another document for future operations, but when this job is completed and a new one is created i don't see an easy way to keep the track of the new id. Here are some solutions that i've tried but that feel terrible for what should be easier:

1: Avoid job.repeat and when job is completed create a new one and store the id before calling callback. This works, but then what is the meaning of repeat? :S
2: Before calling callback() create a query to look for a document in jc with status waiting and type "X" and data "Y". This could also work, but i don't like the idea of adding custom indexes for many fields.
3: Modify the collection observeChanges so when a new item is added a callback tells to update the other collection with the newlyCreated id. This one looks quite promising, but seems like a very ad-hoc solution which would involve writing code for any kind of document that needs to be updated after anyJobCollection gets updated.

So after all of this, is there any other (and easier way) to get the id of the new cloned jobs?
Thanks :)

**Comment by vsivsi** [comment]
Hi, thanks for your question.

You indicate that you need the `_id` value for the new jobs created when an existing job completes and it it set to repeat, but you don't really describe what you need that `_id` for; that is, what functionality are you trying to build that you find to be a challenge. That context would be helpful. Also knowing a little more about how your repeating jobs are structured would help.  Anyway, I'll do the best I can with the details you've provided.

Comments on your three possible solutions:

1.  This is a valid approach. Not all types of jobs are a good fit for using `repeat`. Simplest example would be any job that will conditionally repeat in some way. If you want a notification with the new job `_id` to arrive at the server, then doing that as the last step of the old job (create new job, invoke a server method with _id of new job, ...) Nothing wrong with that approach. The "point of repeat" was to make it trivial to do what I found myself doing manually again and again, write jobs that repeat periodically, or on some more complex schedule.

2.  I'll start by saying what is perhaps obvious: the `_id` values for all jobs are stored in the job-collection itself. They are always there to be discovered using `jc.find(someQuery)`. That was kind of the point of building this package around a Mongo Collection!  Indexing `type` and `status` [is a good idea in any case](https://github.com/vsivsi/meteor-job-collection#performance), because job-collection itself queries against these keys frequently. As for indexing your data, this is a place where you haven't given me enough to detail to understand how you've structured your jobs. It sounds like you may have multiple repeating jobs of the same type, but with different data?  How many? Is the number of such jobs fixed, or dynamic depending on other data?  If it's a relatively small number of such jobs and they don't change very often, I would consider just giving each one its own job type and  "problem solved." But again, I don't really know what you are trying to do or the approach you are taking...

3. Using `jc.find().observe()` (or `.observeChanges()`) is the preferred approach to monitoring the status of a JobCollection for any number of reasons. I use such an approach to [avoid polling in my workers](https://github.com/vsivsi/meteor-job-collection#qtrigger---anywhere) and it works great! I agree that it sounds as though this may be the most promising route. But as you point out, the ease of doing this depends on how you structure your jobs...

To sum up, I think you've identified three valid approaches to solving this problem. I can't think of a fourth that would be superior to one of these.

I'm not seeing an obvious missing feature for job-collection in this. Because jobs can be created anywhere (server, client, via DDP), it's not possible to "register a callback" at the time of job creation for when a job repeats (and it would probably be a security risk to try). I could certainly try to add a callback registration mechanism on the server-side, but if I designed it to be specific to your use case (or other such specific cases) it would be of limited general usefulness and there would be a stream of "can you add this functionality" type requests to keep up with... If I designed a very general solution... well that would look very much like option 3 above (`.observe()` / `.observeChanges()`) and there's no point in reinventing that wheel!

Anyway, I hope this helps.  If its any consolation, the "zombie killer" feature will be in 1.2.0, which I'll be releasing this week. It's on the `dev` branch now if you want to check it out and help test!  Just llok for the `workTimeout` option on these calls:
https://github.com/vsivsi/meteor-job-collection/tree/dev#jcgetworktype-options-callback---anywhere
https://github.com/vsivsi/meteor-job-collection/tree/dev#jq--jcprocessjobstype-options-worker---anywhere

**Comment by tcastelli** [comment]
Thanks for the detailed answer @vsivsi ! 
I use jobCollections for different kinds of "critical" operations inside the server side (for now i don't think about using the client side), and one on them is to collect payments for every user account every X time (defined when getting a new payment plan).
Since payments are susceptible to fail at runtime(because credit card has expired, incorrect data, servers down,...) i thought of using a job that is repeated every X (monthly,yearly, 3 months,...)  and also auto-retries. It really fits the problem and seems easy to manage.

The idea about keeping the _id of the monthly payment job inside the Meteor.users collection is that I can trigger manual reruns/stops or pauses for every user from an admin UI panel.(Multiple users can have the same plan so it's not a trivial query (see below) 
So let's say collecting a payment fails and the next retry is set to every 20 minutes, I would like to retry the operation manually if the client gets in touch without waiting for the next automatic retry.

For this case i have defined different kinds of jobTypes "freePlan" "paidPlanX" "paidPlanY" and for now i only gather the userId in the data field, but this is likely to change in the future, that's why I think i may end having to add a lot of indexs on data.userId, data.XXX, data.YYY for an operation that is not very common in time(otherwise queries will be slow without indexes whenever I have to make them).

I think i will take the 3rd road for now, since option 1 involves duplicating code ( creating the job after a user is registered and every time a job finishes), and not sure about creating indexes for something that is not so common.

And yes I realize this could be to custom to add to JobCollection, but well maybe returning the _id on the server callback on job.done() could be something useful for more use-cases.

**Comment by vsivsi** [comment]
Hi, thanks for the additional info, I understand better now. Just a quick note: the last feature I'm adding to v1.2.0 is a general event emitter on the server for errors and DDP calls. So that the backend can more easily implement custom logging and [status](https://github.com/vsivsi/meteor-job-collection/issues/89) functionality. So rather than using `.observe()`, you could instead do:

`jc.events.on('someEvent', function (msg) {});`

I'm initially using it to re-implement the default logging functionality; but because it's just a plain old node.js [Event Emitter](https://nodejs.org/api/events.html#events_class_events_eventemitter) it should be easy to customize and build on top of.

I'm working on it now on the `events` branch, with the initial implementation working at commit: https://github.com/vsivsi/meteor-job-collection/commit/0859049a260b56b38577a0e0fae674700cf86849

Anyway, thought I'd mention in case you have any input on this...

**Comment by vsivsi** [comment]
This diff more clearly shows the event emitter changes: https://github.com/vsivsi/meteor-job-collection/compare/dev...events

**Comment by tcastelli** [comment]
Thanks I'll have a look now, if I get this correctly, this means that i could add a server callback for when the status of a jc changes to "ready"(after calling .done() this should be triggered since a new one is added) and then get the _id inside the trigger to update the other collection.
If that's the case it would be perfect gonna try reading the code to check it out (thought not really a fan of cofeescript hahaha) :)

Btw does it mean that with 1.2.0 the logging system will be changed to adding console.log() (or whatever) inside every server callback?. What i think would be really useful would be a call to the jc stating which kinds of events have to be logged and a function to do that. SO for example something like this  
    jc.logEvents(["someEvent1","someEvent2"], function(job){if (job.type === "someEvent1") console.log(job.data);
else winston.log("error", job.data);
}

**Comment by vsivsi** [comment]
Hi, okay I thought about it over lunch and I agree that `job.done()` should be able to return the `_id` of a the new job when repeating.

Unfortunately, implementing just that has the potential to break existing code that checks for `ret === true`, so I've added an option `repeatId` to `job.done()` that changes its behavior in this case.

It's implemented on the `done_returns_repeat_id` branch: https://github.com/vsivsi/meteor-job-collection/compare/events...done_returns_repeat_id?expand=1  

Please take a look and let me know what you think.

On logging and events.  What I've done so far in 1.2.0 is add two events, one of which fires for every job-collection DDP Method call: `'error'` and `'call'`. Though implemented with these new events, the default logging behavior is exactly the same as before: if you call `jc.setLogStream(someWriteableStream)` on the server, that stream will get the full firehose log, as it does today. Previously you could override `jc._toLog()` and replace with your own method to format, filter or otherwise change the logging behavior. It was undocumented, but worked. That will still work, but now you can instead add your own listeners to `'call'` and `'error'` events to implement whatever you want... Filtered logging, aggregate stats, anything really.

**Comment by vsivsi** [comment]
I'm going to push hard to release all of this in v1.2.0 tomorrow, so any additional feedback you can get to me quickly will be much appreciated. I really need to wrap up this release so I can move on to other things...

**Comment by tcastelli** [comment]
Thanks this looks great! The interface to keep backwards compatiblity also looks fine for me, this way it's much easier to keep the _ids directly from job.done().
And in terms of logging that's also fine, I just wanted to use winston instead of process.stdout or whatever. (Is it possible to set up setLogStream with a remote logging system?)

**Comment by vsivsi** [comment]
The `setLogStream()` mechanism is really a leftover from when I was developing and testing he package. I decided to leave it in so there would be a standard way to remotely debug, etc. but it was never intended to be (or become) all things to all people. 

The new event based mechanism should allow applications using job-collection to implement whatever they need and prefer.  I haven't personally used Winston, but now you can easily add that for whatever events are significant for your app.

**Comment by tcastelli** [comment]
Yep, that makes sense, anyway seems like it would be difficult to adapat that function to any kind of use, so making custom callback seems a much cleaner solution. 
And now I'm also thinking that what I proposed before about a general events callback is also not so useful since you can define everything separately on its own callback for better traceability and separation. 
Anyway thanks for your work!, I'm refactoring my code to try all the new features whenever you release the next version, tfor now everything that i have tried seems to be working on basic cases :)

**Comment by vsivsi** [comment]
1.2.0 released last night with this functionality, so I'm closing this one.
